#!/usr/bin/env bash
# Nix wrapper script, generated by Nixie (https://github.com/nixie-dev/nixie)
# Nixie (c) Karim Vergnes <me@thesola.io>
# Built using Amber 0.5.1-alpha-nix-dd1b7dc (https://amber-lang.com)

[ "$EUID" -ne 0 ] && { { command -v sudo >/dev/null 2>&1 && __sudo=sudo; } || { command -v doas >/dev/null 2>&1 && __sudo=doas; }; }
split__5_v0() {
    local text_257="${1}"
    local delimiter_258="${2}"
    local result_259=()
    IFS="${delimiter_258}" read -rd '' -a result_259 < <(printf %s "$text_257")
    __status=$?
    ret_split5_v0=("${result_259[@]}")
    return 0
}

join__8_v0() {
    local list_265=("${!1}")
    local delimiter_266="${2}"
    local command_1
    command_1="$(IFS="${delimiter_266}" ; printf "%s
" "${list_265[*]}")"
    __status=$?
    ret_join8_v0="${command_1}"
    return 0
}

parse_int__14_v0() {
    local text_2812="${1}"
    [ -n "${text_2812}" ] && [ "${text_2812}" -eq "${text_2812}" ] 2>/dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_parse_int14_v0=''
        return "${__status}"
    fi
    ret_parse_int14_v0="${text_2812}"
    return 0
}

text_contains__17_v0() {
    local source_22="${1}"
    local search_23="${2}"
    [[ "${source_22}" == *"${search_23}"* ]]
    __status=$?
    ret_text_contains17_v0="$(( __status == 0 ))"
    return 0
}

starts_with__23_v0() {
    local text_26="${1}"
    local prefix_27="${2}"
    [[ "${text_26}" == "${prefix_27}"* ]]
    __status=$?
    ret_starts_with23_v0="$(( __status == 0 ))"
    return 0
}

ends_with__24_v0() {
    local text_2895="${1}"
    local suffix_2896="${2}"
    [[ "${text_2895}" == *"${suffix_2896}" ]]
    __status=$?
    ret_ends_with24_v0="$(( __status == 0 ))"
    return 0
}

slice__25_v0() {
    local text_241="${1}"
    local index_242="${2}"
    local length_243="${3}"
    local result_244=""
    if [ "$(( length_243 == 0 ))" != 0 ]; then
        local __length_2="${text_241}"
        length_243="$(( ${#__length_2} - index_242 ))"
    fi
    if [ "$(( length_243 <= 0 ))" != 0 ]; then
        ret_slice25_v0="${result_244}"
        return 0
    fi
    result_244="${text_241: ${index_242}: ${length_243}}"
    __status=$?
    ret_slice25_v0="${result_244}"
    return 0
}

dir_exists__41_v0() {
    local path_248="${1}"
    [ -d "${path_248}" ]
    __status=$?
    ret_dir_exists41_v0="$(( __status == 0 ))"
    return 0
}

file_exists__42_v0() {
    local path_282="${1}"
    [ -f "${path_282}" ]
    __status=$?
    ret_file_exists42_v0="$(( __status == 0 ))"
    return 0
}

file_write__44_v0() {
    local path_2883="${1}"
    local content_2884="${2}"
    local command_3
    command_3="$(printf '%s
' "${content_2884}" > "${path_2883}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_file_write44_v0=''
        return "${__status}"
    fi
    ret_file_write44_v0="${command_3}"
    return 0
}

dir_create__47_v0() {
    local path_247="${1}"
    dir_exists__41_v0 "${path_247}"
    local ret_dir_exists41_v0__87_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__87_12 ))" != 0 ]; then
        mkdir -p "${path_247}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_dir_create47_v0=''
            return "${__status}"
        fi
    fi
}

array_last__74_v0() {
    local array_2805=("${!1}")
    local __length_4=("${array_2805[@]}")
    local index_2806="$(( ${#__length_4[@]} - 1 ))"
    if [ "$(( index_2806 < 0 ))" != 0 ]; then
        ret_array_last74_v0=''
        return 1
    fi
    ret_array_last74_v0="${array_2805[${index_2806}]}"
    return 0
}

array_pop__77_v0() {
    local array_261=("${1}")
    eval "local array_261_deref_85=(\"\${${array_261[0]}[@]}\")"
    local __length_5=("${array_261_deref_85[@]}")
    local length_262="${#__length_5[@]}"
    local index_263="$(( length_262 - 1 ))"
    if [ "$(( index_263 < 0 ))" != 0 ]; then
        ret_array_pop77_v0=''
        return 1
    fi
    eval "local array_261_deref_86=\"\${${array_261[0]}[${index_263}]}\""
    local element_264="${array_261_deref_86}"
    local slice_upper_6="${index_263}"
    local slice_offset_7=0
    local slice_offset_7=$((${slice_offset_7} > 0 ? ${slice_offset_7} : 0))
    local slice_length_8="$(( slice_upper_6 - slice_offset_7 ))"
    local slice_length_8=$((${slice_length_8} > 0 ? ${slice_length_8} : 0))
    eval "local array_261_deref_87=(\"\${${array_261[0]}[@]:\${slice_offset_7}:\${slice_length_8}}\")"
    eval "${array_261}=(\"\${array_261_deref_87[@]}\")"
    ret_array_pop77_v0="${element_264}"
    return 0
}

array_shift__78_v0() {
    local array_277=("${1}")
    eval "local array_277_deref_88=(\"\${${array_277[0]}[@]}\")"
    local __length_9=("${array_277_deref_88[@]}")
    local length_278="${#__length_9[@]}"
    if [ "$(( length_278 == 0 ))" != 0 ]; then
        ret_array_shift78_v0=''
        return 1
    fi
    eval "local array_277_deref_89=\"\${${array_277[0]}[0]}\""
    local element_279="${array_277_deref_89}"
    local slice_upper_10="${length_278}"
    local slice_offset_11=1
    local slice_offset_11=$((${slice_offset_11} > 0 ? ${slice_offset_11} : 0))
    local slice_length_12="$(( slice_upper_10 - slice_offset_11 ))"
    local slice_length_12=$((${slice_length_12} > 0 ? ${slice_length_12} : 0))
    eval "local array_277_deref_90=(\"\${${array_277[0]}[@]:\${slice_offset_11}:\${slice_length_12}}\")"
    eval "${array_277}=(\"\${array_277_deref_90[@]}\")"
    ret_array_shift78_v0="${element_279}"
    return 0
}

env_var_test__119_v0() {
    local name_2803="${1}"
    [[ ! -z ${!name_2803+z} ]]
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_test119_v0=0
        return 0
    fi
    ret_env_var_test119_v0=1
    return 0
}

env_var_set__121_v0() {
    local name_270="${1}"
    local val_271="${2}"
    export $name_270="$val_271" 2> /dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_set121_v0=''
        return "${__status}"
    fi
}

env_var_get__122_v0() {
    local name_16="${1}"
    local command_13
    command_13="$(printf "%s
" "${!name_16}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_get122_v0=''
        return "${__status}"
    fi
    ret_env_var_get122_v0="${command_13}"
    return 0
}

is_command__124_v0() {
    local command_66="${1}"
    [ -x "$(command -v "${command_66}")" ]
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_is_command124_v0=0
        return 0
    fi
    ret_is_command124_v0=1
    return 0
}

printf__130_v0() {
    local format_38="${1}"
    local args_39=("${!2}")
    args_39=("${format_38}" "${args_39[@]}")
    __status=$?
    printf "${args_39[@]}"
    __status=$?
}

echo_warning__139_v0() {
    local message_268="${1}"
    local array_14=("${message_268}")
    printf__130_v0 "\\x1b[1;3;97;43m%s\\x1b[0m
" array_14[@]
}

echo_error__140_v0() {
    local message_36="${1}"
    local exit_code_37="${2}"
    local array_15=("${message_36}")
    printf__130_v0 "\\x1b[1;3;97;41m%s\\x1b[0m
" array_15[@]
    if [ "$(( exit_code_37 > 0 ))" != 0 ]; then
        exit "${exit_code_37}"
    fi
}

command_16="$(tput tsl)"
__status=$?
tsl_11="${command_16}"
command_17="$(tput fsl)"
__status=$?
fsl_12="${command_17}"
command_18="$(tput smcup)"
__status=$?
smcup_13="${command_18}"
command_19="$(tput rmcup)"
__status=$?
rmcup_14="${command_19}"
env_var_get__122_v0 "TERM"
__status=$?
__TERM_17="${ret_env_var_get122_v0}"
can_set_title__173_v0() {
    local has_statusline_118=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_17}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_20
                command_20="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_11="${command_20}"
                local command_21
                command_21="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_12="${command_21}"
            else
                has_statusline_118=0
            fi
        else
            has_statusline_118=0
        fi
    fi
    ret_can_set_title173_v0="${has_statusline_118}"
    return 0
}

set_title__174_v0() {
    local title_117="${1}"
    can_set_title__173_v0 
    local ret_can_set_title173_v0__43_8="${ret_can_set_title173_v0}"
    if [ "${ret_can_set_title173_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_11}""${title_117}""${fsl_12}"
        __status=$?
    fi
}

enter_alt_buffer__175_v0() {
    >&2 echo ${smcup_13}
    __status=$?
}

exit_alt_buffer__176_v0() {
    >&2 echo ${rmcup_14}
    __status=$?
}

teardown__177_v0() {
    local failure_349="${1}"
    if [ "${failure_349}" != 0 ]; then
        echo "Press any key to continue..."
        read -n 1
        __status=$?
    fi
    set_title__174_v0 ""
    exit_alt_buffer__176_v0 
}

__SELF_18=""
env_var_get__122_v0 "0"
__status=$?
me_19="${ret_env_var_get122_v0}"
text_contains__17_v0 "${me_19}" "/"
ret_text_contains17_v0__15_4="${ret_text_contains17_v0}"
if [ "${ret_text_contains17_v0__15_4}" != 0 ]; then
    starts_with__23_v0 "${me_19}" "/"
    ret_starts_with23_v0__16_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__16_8}" != 0 ]; then
        __SELF_18="${me_19}"
    else
        env_var_get__122_v0 "PWD"
        __status=$?
        __PWD_28="${ret_env_var_get122_v0}"
        command_22="$(readlink ${me_19})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_18="${__PWD_28}/${me_19}"
        fi
        rl_29="${command_22}"
        starts_with__23_v0 "${rl_29}" "/"
        ret_starts_with23_v0__27_17="${ret_starts_with23_v0}"
        if [ "$([ "_${rl_29}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_18="${__SELF_18}"
        elif [ "$(( ! ret_starts_with23_v0__27_17 ))" != 0 ]; then
            __SELF_18="${__PWD_28}/${rl_29}"
        else
            __SELF_18="${rl_29}"
        fi
    fi
else
    echo_error__140_v0 "This script must be run from an absolute or relative path." 1
fi
exists_newer__180_v0() {
    local left_2809="${1}"
    local right_2810="${2}"
    local stat_cmd_2811="stat -c %W"
    local command_23
    command_23="$(uname -s)"
    __status=$?
    if [ "$([ "_${command_23}" != "_Darwin" ]; echo $?)" != 0 ]; then
        stat_cmd_2811="stat -f %B"
    fi
    local command_24
    command_24="$(${stat_cmd_2811} ${left_2809})"
    __status=$?
    parse_int__14_v0 "${command_24}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer180_v0=0
        return 0
    fi
    local left_time_2813="${ret_parse_int14_v0}"
    local command_25
    command_25="$(${stat_cmd_2811} ${right_2810})"
    __status=$?
    parse_int__14_v0 "${command_25}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer180_v0=0
        return 0
    fi
    local right_time_2814="${ret_parse_int14_v0}"
    ret_exists_newer180_v0="$(( left_time_2813 >= right_time_2814 ))"
    return 0
}

bail__181_v0() {
    local message_115="${1}"
    local archive_116="${2}"
    exit_alt_buffer__176_v0 
    set_title__174_v0 ""
    echo_error__140_v0 "${message_115}" 0
    if [ "${archive_116}" != 0 ]; then
        echo_error__140_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

get_self__182_v0() {
    ret_get_self182_v0="${__SELF_18}"
    return 0
}

dump_archive__183_v0() {
    local command_26
    command_26="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_114="${command_26}"
    cat ${__SELF_18} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_114}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__181_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive183_v0="${dest_114}"
    return 0
}

untar__184_v0() {
    local member_112="${1}"
    local dump_113="${2}"
    dump_archive__183_v0 
    local archive_119="${ret_dump_archive183_v0}"
    local tar_cmd_120="tar -x -f ${archive_119} ${member_112}"
    if [ "${dump_113}" != 0 ]; then
        tar_cmd_120="tar -x -O -f ${archive_119} ${member_112}"
    fi
    local command_27
    command_27="$(${tar_cmd_120})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_121="${__status}"
        rm ${archive_119}
        __status=$?
        ret_untar184_v0=''
        return "${tar_status_121}"
    fi
    local tar_out_122="${command_27}"
    rm ${archive_119}
    __status=$?
    if [ "${dump_113}" != 0 ]; then
        ret_untar184_v0="${tar_out_122}"
        return 0
    else
        ret_untar184_v0="${member_112}"
        return 0
    fi
}

check_deps__185_v0() {
    local deps_63=("${!1}")
    local missing_64=()
    for dep_65 in "${deps_63[@]}"; do
        is_command__124_v0 "${dep_65}"
        local ret_is_command124_v0__145_16="${ret_is_command124_v0}"
        if [ "$(( ! ret_is_command124_v0__145_16 ))" != 0 ]; then
            missing_64+=("${dep_65}")
        fi
    done
    local __length_30=("${missing_64[@]}")
    if [ "$(( ${#__length_30[@]} > 0 ))" != 0 ]; then
        echo_error__140_v0 "The following commands are missing:" 0
        for cmd_67 in "${missing_64[@]}"; do
            echo_error__140_v0 "- ${cmd_67}" 0
        done
        echo_error__140_v0 "Use your distribution's package manager to install them, then try again." 0
        ret_check_deps185_v0=''
        return 1
    fi
}

get_osname__195_v0() {
    local command_31
    command_31="$(uname -s)"
    __status=$?
    ret_get_osname195_v0="${command_31}"
    return 0
}

get_machine__196_v0() {
    local command_32
    command_32="$(uname -m)"
    __status=$?
    local machine_2820="${command_32}"
    get_osname__195_v0 
    local ret_get_osname195_v0__23_8="${ret_get_osname195_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__23_8}" == "_Darwin" ]; echo $?) && $([ "_${machine_2820}" != "_arm64" ]; echo $?) ))" != 0 ]; then
        ret_get_machine196_v0="aarch64"
        return 0
    fi
    ret_get_machine196_v0="${machine_2820}"
    return 0
}

get_system__197_v0() {
    get_osname__195_v0 
    local osname_2819="${ret_get_osname195_v0}"
    get_machine__196_v0 
    local machine_2821="${ret_get_machine196_v0}"
    ret_get_system197_v0="${osname_2819}.${machine_2821}"
    return 0
}

get_nix_root__199_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_249="${ret_env_var_get122_v0}"
    get_osname__195_v0 
    local osname_250="${ret_get_osname195_v0}"
    local result_251=""
    if [ "$([ "_${osname_250}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_251="${userhome_249}/Library/Nix"
    else
        result_251="${userhome_249}/.local/share/nix/root"
    fi
    mkdir -p ${result_251}
    __status=$?
    ret_get_nix_root199_v0="${result_251}"
    return 0
}

get_cache_root__200_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_253="${ret_env_var_get122_v0}"
    get_osname__195_v0 
    local osname_254="${ret_get_osname195_v0}"
    local result_255=""
    if [ "$([ "_${osname_254}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_255="${userhome_253}/Library/Caches"
    else
        result_255="${userhome_253}/.cache"
    fi
    mkdir -p ${result_255}
    __status=$?
    ret_get_cache_root200_v0="${result_255}"
    return 0
}

get_repo_root__201_v0() {
    get_self__182_v0 
    local ret_get_self182_v0__85_24="${ret_get_self182_v0}"
    split__5_v0 "${ret_get_self182_v0__85_24}" "/"
    local self_a_260=("${ret_split5_v0[@]}")
    array_pop__77_v0 "self_a_260"
    __status=$?
    join__8_v0 self_a_260[@] "/"
    local ret_join8_v0__88_26="${ret_join8_v0}"
    local self_dir_267="/""${ret_join8_v0__88_26}"
    local command_33
    command_33="$(git -C ${self_dir_267} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__139_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root201_v0="${self_dir_267}"
        return 0
    fi
    ret_get_repo_root201_v0="${command_33}"
    return 0
}

cmd_help__214_v0() {
    env_var_get__122_v0 "NIXIE_VERSION"
    __status=$?
    local __NIXIE_VERSION_246="${ret_env_var_get122_v0}"
    echo "Nix wrapper script, generated by Nixie ${__NIXIE_VERSION_246}"
    printf '%s\n' ""
    echo "Available --nixie- options:"
    echo "  --nixie-help            Show this help message and exit."
    echo "  --nixie-print-config    Print this script's configuration."
    echo "  --nixie-extract         Unpack the resources archive into nixie/"
    echo "  --nixie-cleanup         Delete local Nix build files"
    echo "  --nixie-ignore-system   Behave as if Nix was not installed."
    exit 0
}

cmd_print_config__215_v0() {
    untar__184_v0 "features" 1
    __status=$?
    local ret_untar184_v0__32_16="${ret_untar184_v0}"
    printf '%s\n' "${ret_untar184_v0__32_16}"
    exit 0
}

cmd_extract__216_v0() {
    dir_create__47_v0 "nixie"
    __status=$?
    cd "nixie" || exit
    untar__184_v0 "" 0
    __status=$?
    exit 0
}

cmd_cleanup__217_v0() {
    get_nix_root__199_v0 
    local nix_root_252="${ret_get_nix_root199_v0}"
    get_cache_root__200_v0 
    local cache_root_256="${ret_get_cache_root200_v0}"
    get_repo_root__201_v0 
    local repo_root_269="${ret_get_repo_root201_v0}"
    echo "Removing local Nix channels and build files..."
    chmod -R +wx ${repo_root_269}/.nixie 2>/dev/null
    __status=$?
    rm -rf ${repo_root_269}/.nixie
    __status=$?
    echo "Removing user Nix store..."
    chmod -R +wx ${nix_root_252} 2>/dev/null
    __status=$?
    rm -rf ${nix_root_252}
    __status=$?
    echo "Removing retrieved Nix binaries..."
    rm -rf ${cache_root_256}/nix-static ${cache_root_256}/nix-lib ${cache_root_256}/nix-deps
    __status=$?
    exit 0
}

opt_ignore_system__218_v0() {
    >&2 echo "Ignoring system-wide Nix for testing purposes."
    __status=$?
    >&2 echo "Re-run without the --nixie-ignore-system flag to import the single-user"
    __status=$?
    >&2 echo "Nix store into the system store."
    __status=$?
    env_var_set__121_v0 "nosystem" "1"
    __status=$?
}

opt_no_precompiled__219_v0() {
    >&2 echo "Ignoring precompiled binaries for testing purposes."
    __status=$?
    >&2 echo "This implies --nixie-ignore-system."
    __status=$?
    env_var_set__121_v0 "nobins" "1"
    __status=$?
    env_var_set__121_v0 "nosystem" "1"
    __status=$?
}

notfound__220_v0() {
    local cmd_272="${1}"
    env_var_get__122_v0 "0"
    __status=$?
    local self_273="${ret_env_var_get122_v0}"
    echo_error__140_v0 "No such option: --nixie-${cmd_272}. Run '${self_273} --nixie-help' for available options." 1
}

eval_cmd__221_v0() {
    local cmd_245="${1}"
    if [ "$([ "_${cmd_245}" != "_help" ]; echo $?)" != 0 ]; then
        cmd_help__214_v0 
    elif [ "$([ "_${cmd_245}" != "_print-config" ]; echo $?)" != 0 ]; then
        cmd_print_config__215_v0 
    elif [ "$([ "_${cmd_245}" != "_extract" ]; echo $?)" != 0 ]; then
        cmd_extract__216_v0 
    elif [ "$([ "_${cmd_245}" != "_cleanup" ]; echo $?)" != 0 ]; then
        cmd_cleanup__217_v0 
    elif [ "$([ "_${cmd_245}" != "_ignore-system" ]; echo $?)" != 0 ]; then
        opt_ignore_system__218_v0 
    elif [ "$([ "_${cmd_245}" != "_no-precompiled" ]; echo $?)" != 0 ]; then
        opt_no_precompiled__219_v0 
    else
        notfound__220_v0 "${cmd_245}"
    fi
}

catch_args__222_v0() {
    local args_237=("${1}")
    eval "local args_237_deref_91=(\"\${${args_237[0]}[@]}\")"
    local local_args_238=("${args_237_deref_91[@]}")
    eval "${args_237}=()"
    for arg_239 in "${local_args_238[@]}"; do
        local cmd_240=""
        starts_with__23_v0 "${arg_239}" "--nixie-"
        local ret_starts_with23_v0__110_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__110_12}" != 0 ]; then
            local __length_35="--nixie-"
            slice__25_v0 "${arg_239}" "${#__length_35}" 0
            cmd_240="${ret_slice25_v0}"
            eval_cmd__221_v0 "${cmd_240}"
        else
            eval "${args_237}+=(\"\${arg_239}\")"
        fi
    done
}

file_download__326_v0() {
    local url_2833="${1}"
    local path_2834="${2}"
    is_command__124_v0 "curl"
    local ret_is_command124_v0__15_9="${ret_is_command124_v0}"
    is_command__124_v0 "wget"
    local ret_is_command124_v0__18_9="${ret_is_command124_v0}"
    is_command__124_v0 "aria2c"
    local ret_is_command124_v0__21_9="${ret_is_command124_v0}"
    if [ "${ret_is_command124_v0__15_9}" != 0 ]; then
        curl -L -o "${path_2834}" "${url_2833}">/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command124_v0__18_9}" != 0 ]; then
        wget "${url_2833}" -P "${path_2834}">/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command124_v0__21_9}" != 0 ]; then
        aria2c "${url_2833}" -d "${path_2834}">/dev/null 2>&1
        __status=$?
    else
        ret_file_download326_v0=''
        return 1
    fi
}

cachix_url__333_v0() {
    local derivation_2830="${1}"
    local member_2831="${2}"
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    local __SOURCE_CACHE_2832="${ret_env_var_get122_v0}"
    ret_cachix_url333_v0="https://${__SOURCE_CACHE_2832}/serve/${derivation_2830}/${member_2831}"
    return 0
}

pull_binary__335_v0() {
    local member_2825="${1}"
    local dest_2826="${2}"
    env_var_get__122_v0 "NIX_BINS_DERIVATION"
    __status=$?
    local __NIX_BINS_DERIVATION_2827="${ret_env_var_get122_v0}"
    untar__184_v0 "${member_2825}" 0
    __status=$?
    local where_2828="${ret_untar184_v0}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        local command_37
        command_37="$(mktemp -t nixie_${member_2825}_XXXXXXXX)"
        __status=$?
        local tmpf_2829="${command_37}"
        cachix_url__333_v0 "${__NIX_BINS_DERIVATION_2827}" "${member_2825}"
        local ret_cachix_url333_v0__89_23="${ret_cachix_url333_v0}"
        file_download__326_v0 "${ret_cachix_url333_v0__89_23}" "${tmpf_2829}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_binary335_v0=''
            return "${__status}"
        fi
        where_2828="${tmpf_2829}"
    fi
    mv "${where_2828}" "${dest_2826}"
    __status=$?
}

command_38="$(tput tsl)"
__status=$?
tsl_40="${command_38}"
command_39="$(tput fsl)"
__status=$?
fsl_41="${command_39}"
command_40="$(tput smcup)"
__status=$?
command_41="$(tput rmcup)"
__status=$?
env_var_get__122_v0 "TERM"
__status=$?
__TERM_44="${ret_env_var_get122_v0}"
can_set_title__352_v0() {
    local has_statusline_2851=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_44}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_42
                command_42="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_40="${command_42}"
                local command_43
                command_43="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_41="${command_43}"
            else
                has_statusline_2851=0
            fi
        else
            has_statusline_2851=0
        fi
    fi
    ret_can_set_title352_v0="${has_statusline_2851}"
    return 0
}

set_title__353_v0() {
    local title_2850="${1}"
    can_set_title__352_v0 
    local ret_can_set_title352_v0__43_8="${ret_can_set_title352_v0}"
    if [ "${ret_can_set_title352_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_40}""${title_2850}""${fsl_41}"
        __status=$?
    fi
}

command_44="$(tput tsl)"
__status=$?
tsl_45="${command_44}"
command_45="$(tput fsl)"
__status=$?
fsl_46="${command_45}"
command_46="$(tput smcup)"
__status=$?
command_47="$(tput rmcup)"
__status=$?
rmcup_48="${command_47}"
env_var_get__122_v0 "TERM"
__status=$?
__TERM_49="${ret_env_var_get122_v0}"
can_set_title__372_v0() {
    local has_statusline_2864=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_49}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_48
                command_48="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_45="${command_48}"
                local command_49
                command_49="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_46="${command_49}"
            else
                has_statusline_2864=0
            fi
        else
            has_statusline_2864=0
        fi
    fi
    ret_can_set_title372_v0="${has_statusline_2864}"
    return 0
}

set_title__373_v0() {
    local title_2863="${1}"
    can_set_title__372_v0 
    local ret_can_set_title372_v0__43_8="${ret_can_set_title372_v0}"
    if [ "${ret_can_set_title372_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_45}""${title_2863}""${fsl_46}"
        __status=$?
    fi
}

exit_alt_buffer__375_v0() {
    >&2 echo ${rmcup_48}
    __status=$?
}

__SELF_50=""
env_var_get__122_v0 "0"
__status=$?
me_51="${ret_env_var_get122_v0}"
text_contains__17_v0 "${me_51}" "/"
ret_text_contains17_v0__15_4="${ret_text_contains17_v0}"
if [ "${ret_text_contains17_v0__15_4}" != 0 ]; then
    starts_with__23_v0 "${me_51}" "/"
    ret_starts_with23_v0__16_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__16_8}" != 0 ]; then
        __SELF_50="${me_51}"
    else
        env_var_get__122_v0 "PWD"
        __status=$?
        __PWD_52="${ret_env_var_get122_v0}"
        command_50="$(readlink ${me_51})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_50="${__PWD_52}/${me_51}"
        fi
        rl_53="${command_50}"
        starts_with__23_v0 "${rl_53}" "/"
        ret_starts_with23_v0__27_17="${ret_starts_with23_v0}"
        if [ "$([ "_${rl_53}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_50="${__SELF_50}"
        elif [ "$(( ! ret_starts_with23_v0__27_17 ))" != 0 ]; then
            __SELF_50="${__PWD_52}/${rl_53}"
        else
            __SELF_50="${rl_53}"
        fi
    fi
else
    echo_error__140_v0 "This script must be run from an absolute or relative path." 1
fi
bail__380_v0() {
    local message_2861="${1}"
    local archive_2862="${2}"
    exit_alt_buffer__375_v0 
    set_title__373_v0 ""
    echo_error__140_v0 "${message_2861}" 0
    if [ "${archive_2862}" != 0 ]; then
        echo_error__140_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

get_self__381_v0() {
    ret_get_self381_v0="${__SELF_50}"
    return 0
}

dump_archive__382_v0() {
    local command_51
    command_51="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_2860="${command_51}"
    cat ${__SELF_50} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_2860}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__380_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive382_v0="${dest_2860}"
    return 0
}

untar__383_v0() {
    local member_2858="${1}"
    local dump_2859="${2}"
    dump_archive__382_v0 
    local archive_2865="${ret_dump_archive382_v0}"
    local tar_cmd_2866="tar -x -f ${archive_2865} ${member_2858}"
    if [ "${dump_2859}" != 0 ]; then
        tar_cmd_2866="tar -x -O -f ${archive_2865} ${member_2858}"
    fi
    local command_52
    command_52="$(${tar_cmd_2866})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_2867="${__status}"
        rm ${archive_2865}
        __status=$?
        ret_untar383_v0=''
        return "${tar_status_2867}"
    fi
    local tar_out_2868="${command_52}"
    rm ${archive_2865}
    __status=$?
    if [ "${dump_2859}" != 0 ]; then
        ret_untar383_v0="${tar_out_2868}"
        return 0
    else
        ret_untar383_v0="${member_2858}"
        return 0
    fi
}

get_osname__386_v0() {
    local command_53
    command_53="$(uname -s)"
    __status=$?
    ret_get_osname386_v0="${command_53}"
    return 0
}

get_cache_root__391_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_2844="${ret_env_var_get122_v0}"
    get_osname__386_v0 
    local osname_2845="${ret_get_osname386_v0}"
    local result_2846=""
    if [ "$([ "_${osname_2845}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_2846="${userhome_2844}/Library/Caches"
    else
        result_2846="${userhome_2844}/.cache"
    fi
    mkdir -p ${result_2846}
    __status=$?
    ret_get_cache_root391_v0="${result_2846}"
    return 0
}

get_repo_root__392_v0() {
    get_self__381_v0 
    local ret_get_self381_v0__85_24="${ret_get_self381_v0}"
    split__5_v0 "${ret_get_self381_v0__85_24}" "/"
    local self_a_2839=("${ret_split5_v0[@]}")
    array_pop__77_v0 "self_a_2839"
    __status=$?
    join__8_v0 self_a_2839[@] "/"
    local ret_join8_v0__88_26="${ret_join8_v0}"
    local self_dir_2840="/""${ret_join8_v0__88_26}"
    local command_54
    command_54="$(git -C ${self_dir_2840} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__139_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root392_v0="${self_dir_2840}"
        return 0
    fi
    ret_get_repo_root392_v0="${command_54}"
    return 0
}

get_source_root__396_v0() {
    get_repo_root__392_v0 
    local repo_root_2841="${ret_get_repo_root392_v0}"
    ret_get_source_root396_v0="${repo_root_2841}/.nixie/sources"
    return 0
}

cachix_url__406_v0() {
    local derivation_2873="${1}"
    local member_2874="${2}"
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    local __SOURCE_CACHE_2875="${ret_env_var_get122_v0}"
    ret_cachix_url406_v0="https://${__SOURCE_CACHE_2875}/serve/${derivation_2873}/${member_2874}"
    return 0
}

pull_source_file__407_v0() {
    local member_2853="${1}"
    local dest_2854="${2}"
    env_var_get__122_v0 "SOURCE_DERIVATION"
    __status=$?
    local __SOURCE_DERIVATION_2855="${ret_env_var_get122_v0}"
    local where_2856=""
    local my_status_2857=1
    env_var_test__119_v0 "_NIXIE_TESTING_SKIP_TARBALL"
    local ret_env_var_test119_v0__36_12="${ret_env_var_test119_v0}"
    if [ "$(( ! ret_env_var_test119_v0__36_12 ))" != 0 ]; then
        untar__383_v0 "sources/${member_2853}" 0
        __status=$?
        where_2856="${ret_untar383_v0}"
        my_status_2857="${__status}"
    fi
    env_var_test__119_v0 "_NIXIE_TESTING_SOURCES_DIR"
    local ret_env_var_test119_v0__41_8="${ret_env_var_test119_v0}"
    if [ "$(( ret_env_var_test119_v0__41_8 && $(( my_status_2857 != 0 )) ))" != 0 ]; then
        env_var_get__122_v0 "_NIXIE_TESTING_SOURCES_DIR"
        __status=$?
        local srcdir_2869="${ret_env_var_get122_v0}"
        local command_55
        command_55="$(mktemp -t -d nixie_${member_2853}_XXXXXXXX)"
        __status=$?
        local tmpd_2870="${command_55}"
        file_exists__42_v0 "${srcdir_2869}/${member_2853}.tar.gz"
        local ret_file_exists42_v0__45_12="${ret_file_exists42_v0}"
        if [ "${ret_file_exists42_v0__45_12}" != 0 ]; then
            gzip -d -c ${srcdir_2869}/${member_2853}.tar.gz | tar -x -C ${tmpd_2870}
            __status=$?
            my_status_2857="${__status}"
            where_2856="${tmpd_2870}/${member_2853}"
        else
            my_status_2857=1
        fi
    fi
    if [ "$(( my_status_2857 != 0 ))" != 0 ]; then
        local command_56
        command_56="$(mktemp -t nixie_src_XXXXXXXX.tgz)"
        __status=$?
        local tmpf_2871="${command_56}"
        local command_57
        command_57="$(mktemp -t -d nixie_${member_2853}_XXXXXXXX)"
        __status=$?
        local tmpd_2872="${command_57}"
        cachix_url__406_v0 "${__SOURCE_DERIVATION_2855}" "${member_2853}.tar.gz"
        local ret_cachix_url406_v0__58_23="${ret_cachix_url406_v0}"
        file_download__326_v0 "${ret_cachix_url406_v0__58_23}" "${tmpf_2871}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file407_v0=''
            return "${__status}"
        fi
        gzip -d -c ${tmpf_2871} | tar -x -C ${tmpd_2872}
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file407_v0=''
            return "${__status}"
        fi
        rm -f ${tmpf_2871}
        __status=$?
        where_2856="${tmpd_2872}/${member_2853}"
    fi
    rm -rf ${dest_2854}
    __status=$?
    mv "${where_2856}" "${dest_2854}"
    __status=$?
}

step_current_55=1
pkg_exists__416_v0() {
    local package_2852="${1}"
    pkg-config ${package_2852}
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_pkg_exists416_v0=0
        return 0
    fi
    ret_pkg_exists416_v0=1
    return 0
}

step_title__417_v0() {
    local name_2848="${1}"
    env_var_get__122_v0 "step_total"
    __status=$?
    local step_total_2849="${ret_env_var_get122_v0}"
    clear
    __status=$?
    set_title__353_v0 "Building Nix: ${name_2848} (${step_current_55}/${step_total_2849})"
    step_current_55="$(( step_current_55 + 1 ))"
}

get_source_root__418_v0() {
    get_repo_root__392_v0 
    local repo_root_2842="${ret_get_repo_root392_v0}"
    ret_get_source_root418_v0="${repo_root_2842}/.nixie/sources"
    return 0
}

build_openssl_inner__423_v0() {
    get_dll_ext__389_v0 
    local dll_ext_520="${ret_get_dll_ext389_v0}"
    get_cache_root__391_v0 
    local cache_root_524="${ret_get_cache_root391_v0}"
    chmod +x ./config
    __status=$?
    ./config
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner423_v0=''
        return "${__status}"
    fi
    make_headers__422_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner423_v0=''
        return "${__status}"
    fi
    make libcrypto.${dll_ext_520} libcrypto.pc
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner423_v0=''
        return "${__status}"
    fi
    cp ./libcrypto.* ${cache_root_524}/nix-deps/lib/
    __status=$?
    cp ./libcrypto.pc ${cache_root_524}/nix-deps/lib/pkgconfig
    __status=$?
    cp -r ./include ${cache_root_524}/nix-deps/
    __status=$?
}

build_openssl__424_v0() {
    get_source_root__418_v0 
    local source_root_2843="${ret_get_source_root418_v0}"
    get_cache_root__391_v0 
    step_title__417_v0 "libcrypto"
    pkg_exists__416_v0 "libcrypto"
    local ret_pkg_exists416_v0__56_8="${ret_pkg_exists416_v0}"
    if [ "${ret_pkg_exists416_v0__56_8}" != 0 ]; then
        ret_build_openssl424_v0=0
        return 0
    fi
    env_var_test__119_v0 "OPENSSL_LIBS"
    local ret_env_var_test119_v0__58_8="${ret_env_var_test119_v0}"
    env_var_test__119_v0 "OPENSSL_CFLAGS"
    local ret_env_var_test119_v0__58_41="${ret_env_var_test119_v0}"
    if [ "$(( ret_env_var_test119_v0__58_8 && ret_env_var_test119_v0__58_41 ))" != 0 ]; then
        ret_build_openssl424_v0=0
        return 0
    fi
    pull_source_file__407_v0 "openssl" "${source_root_2843}/openssl"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl424_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2843}/openssl && build_openssl_inner__423_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl424_v0=''
        return "${__status}"
    fi
}

build_lowdown_inner__434_v0() {
    get_cache_root__391_v0 
    local cache_root_784="${ret_get_cache_root391_v0}"
    ./configure PREFIX=${cache_root_784}/nix-deps
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner434_v0=''
        return "${__status}"
    fi
    make
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner434_v0=''
        return "${__status}"
    fi
    get_osname__386_v0 
    local ret_get_osname386_v0__26_8="${ret_get_osname386_v0}"
    if [ "$([ "_${ret_get_osname386_v0__26_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        macos_build_post__433_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_build_lowdown_inner434_v0=''
            return "${__status}"
        fi
    fi
    make install_shared
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner434_v0=''
        return "${__status}"
    fi
}

build_lowdown__435_v0() {
    get_source_root__418_v0 
    local source_root_2885="${ret_get_source_root418_v0}"
    get_cache_root__391_v0 
    step_title__417_v0 "lowdown"
    pkg_exists__416_v0 "lowdown"
    local ret_pkg_exists416_v0__41_8="${ret_pkg_exists416_v0}"
    if [ "${ret_pkg_exists416_v0__41_8}" != 0 ]; then
        ret_build_lowdown435_v0=0
        return 0
    fi
    pull_source_file__407_v0 "lowdown" "${source_root_2885}/lowdown"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown435_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2885}/lowdown && build_lowdown_inner__434_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown435_v0=''
        return "${__status}"
    fi
}

build_nlohmann_json__444_v0() {
    get_source_root__418_v0 
    local source_root_2880="${ret_get_source_root418_v0}"
    get_cache_root__391_v0 
    local cache_root_2881="${ret_get_cache_root391_v0}"
    step_title__417_v0 "nlohmann_json"
    pkg_exists__416_v0 "nlohmann_json"
    local ret_pkg_exists416_v0__21_8="${ret_pkg_exists416_v0}"
    if [ "${ret_pkg_exists416_v0__21_8}" != 0 ]; then
        ret_build_nlohmann_json444_v0=0
        return 0
    fi
    pull_source_file__407_v0 "nlohmann_json" "${source_root_2880}/nlohmann_json"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json444_v0=''
        return "${__status}"
    fi
    local command_58
    command_58="$(grep "^version:" ${source_root_2880}/nlohmann_json/wsjcpp.yml | cut -d '"' -f 2 | cut -d 'v' -f 2)"
    __status=$?
    local version_2882="${command_58}"
    file_write__44_v0 "${cache_root_2881}/nix-deps/lib/pkgconfig/nlohmann_json.pc" "Name: nlohmann_json
Version: ${version_2882}
Description: JSON for Modern C++
Cflags: -I${source_root_2880}/nlohmann_json/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json444_v0=''
        return "${__status}"
    fi
}

modules_56=("predef" "chrono" "container" "context" "coroutine" "system" "thread")
find_boost_libs__453_v0() {
    local libs_2877=("${!1}")
    for lib_2878 in "${libs_2877[@]}"; do
        local libname_2879="libboost_${lib_2878}*"
        file_exists__42_v0 "/usr/lib/${libname_2879}"
        local ret_file_exists42_v0__23_20="${ret_file_exists42_v0}"
        file_exists__42_v0 "/usr/local/lib/${libname_2879}"
        local ret_file_exists42_v0__24_20="${ret_file_exists42_v0}"
        if [ "$(( ! $(( ret_file_exists42_v0__23_20 || ret_file_exists42_v0__24_20 )) ))" != 0 ]; then
            ret_find_boost_libs453_v0=0
            return 0
        fi
        dir_exists__41_v0 "/usr/include/boost/${lib_2878}"
        local ret_dir_exists41_v0__26_20="${ret_dir_exists41_v0}"
        dir_exists__41_v0 "/usr/local/include/boost/${lib_2878}"
        local ret_dir_exists41_v0__27_20="${ret_dir_exists41_v0}"
        if [ "$(( ! $(( ret_dir_exists41_v0__26_20 || ret_dir_exists41_v0__27_20 )) ))" != 0 ]; then
            ret_find_boost_libs453_v0=0
            return 0
        fi
    done
    ret_find_boost_libs453_v0=1
    return 0
}

build_boost_inner__454_v0() {
    local args_613=("variant=release" "link=static" "--stagedir=.")
    for mod_614 in "${modules_56[@]}"; do
        args_613+=("--with-${mod_614}")
    done
    ./bootstrap.sh
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner454_v0=''
        return "${__status}"
    fi
    ./b2 "${args_613[@]}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner454_v0=''
        return "${__status}"
    fi
}

build_boost__455_v0() {
    get_source_root__418_v0 
    local source_root_2876="${ret_get_source_root418_v0}"
    step_title__417_v0 "boost"
    local array_62=("atomic")
    local array_add_63=("${array_62[@]}" "${modules_56[@]}")
    find_boost_libs__453_v0 array_add_63[@]
    local ret_find_boost_libs453_v0__56_8="${ret_find_boost_libs453_v0}"
    if [ "${ret_find_boost_libs453_v0__56_8}" != 0 ]; then
        ret_build_boost455_v0=0
        return 0
    fi
    pull_source_file__407_v0 "boost" "${source_root_2876}/boost"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost455_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2876}/boost && build_boost_inner__454_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost455_v0=''
        return "${__status}"
    fi
    env_var_set__121_v0 "BOOST_ROOT" "${source_root_2876}/boost"
    __status=$?
    export BOOST_ROOT
    __status=$?
}

build_autoconf_dep__463_v0() {
    local lib_name_2887="${1}"
    local inc_prefix_2888="${2}"
    get_source_root__418_v0 
    local source_root_2889="${ret_get_source_root418_v0}"
    get_cache_root__391_v0 
    local cache_root_2890="${ret_get_cache_root391_v0}"
    local my_source_2891="${source_root_2889}/${lib_name_2887}"
    step_title__417_v0 "${lib_name_2887}"
    pkg_exists__416_v0 "${lib_name_2887}"
    local ret_pkg_exists416_v0__26_8="${ret_pkg_exists416_v0}"
    if [ "${ret_pkg_exists416_v0__26_8}" != 0 ]; then
        ret_build_autoconf_dep463_v0=''
        return 0
    fi
    pull_source_file__407_v0 "${lib_name_2887}" "${my_source_2891}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep463_v0=''
        return "${__status}"
    fi
    ( unset C_INCLUDE_PATH CPLUS_INCLUDE_PATH     && cd ${my_source_2891}     && ./configure --prefix=${cache_root_2890}/nix-deps     && make && make install )
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep463_v0=''
        return "${__status}"
    fi
}

build_nix_inner__473_v0() {
    get_source_root__418_v0 
    local source_root_1083="${ret_get_source_root418_v0}"
    local venv_1084="${source_root_1083}/nix/venv"
    mkdir build && cd build
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner473_v0=''
        return "${__status}"
    fi
    ${venv_1084}/bin/meson setup -Dlibstore:seccomp-sandboxing=disabled                             -Dlibcmd:readline-flavor=editline                             -Dlibexpr:gc=disabled                             -Dlibutil:cpuid=disabled                             -Ddoc-gen=false                             -Dunit-tests=false                             -Dbindings=false                             ..
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner473_v0=''
        return "${__status}"
    fi
    ${venv_1084}/bin/ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner473_v0=''
        return "${__status}"
    fi
}

build_nix__474_v0() {
    get_source_root__418_v0 
    local source_root_2892="${ret_get_source_root418_v0}"
    get_cache_root__391_v0 
    local cache_root_2893="${ret_get_cache_root391_v0}"
    local venv_2894="${source_root_2892}/nix/venv"
    step_title__417_v0 "nix"
    pull_source_file__407_v0 "nix" "${source_root_2892}/nix"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix474_v0=''
        return "${__status}"
    fi
    python3 -m venv --system-site-packages "${venv_2894}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix474_v0=''
        return "${__status}"
    fi
    export LIBRARY_PATH=${cache_root_2893}/nix-deps/lib:$LIBRARY_PATH
    __status=$?
    export PKG_CONFIG_PATH=${cache_root_2893}/nix-deps/lib/pkgconfig:${cache_root_2893}/nix-deps/share/pkgconfig:$PKG_CONFIG_PATH
    __status=$?
    ${venv_2894}/bin/pip install meson ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix474_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2892}/nix && build_nix_inner__473_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix474_v0=''
        return "${__status}"
    fi
    mv "${source_root_2892}/nix/src/nix/nix" "${cache_root_2893}/nix-static"
    __status=$?
}

darwin_export_sdk__476_v0() {
    local command_64
    command_64="$(xcrun --show-sdk-path)"
    __status=$?
    local sdk_path_2836="${command_64}"
    dir_exists__41_v0 "${sdk_path_2836}"
    local ret_dir_exists41_v0__30_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__30_12 ))" != 0 ]; then
        bail__181_v0 "The macOS SDK from Xcode or CommandLineTools is required to build Nix." 0
    fi
    local sdk_libs_2837="${sdk_path_2836}/usr/lib"
    local sdk_cflags_2838="-I${sdk_path_2836}/usr/include"
    env_var_set__121_v0 "LIBCURL_LIBS" "${sdk_libs_2837}"
    __status=$?
    env_var_set__121_v0 "LIBCURL_CFLAGS" "${sdk_cflags_2838}"
    __status=$?
    env_var_set__121_v0 "LIBARCHIVE_LIBS" "${sdk_libs_2837}"
    __status=$?
    env_var_set__121_v0 "LIBARCHIVE_CFLAGS" "${sdk_cflags_2838}"
    __status=$?
    env_var_set__121_v0 "OPENSSL_LIBS" "${sdk_libs_2837}"
    __status=$?
    env_var_set__121_v0 "OPENSSL_CFLAGS" "${sdk_cflags_2838}"
    __status=$?
    export LIBCURL_LIBS LIBCURL_CFLAGS                   LIBARCHIVE_LIBS LIBARCHIVE_CFLAGS                   OPENSSL_LIBS OPENSSL_CFLAGS
    __status=$?
}

try_build_nix__477_v0() {
    get_cache_root__200_v0 
    local cache_root_2835="${ret_get_cache_root200_v0}"
    local array_65=("cc" "c++" "pkg-config" "make" "flex" "bison" "perl")
    check_deps__185_v0 array_65[@]
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "Missing required dependencies to build from source." 0
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__60_8="${ret_get_osname195_v0}"
    if [ "$([ "_${ret_get_osname195_v0__60_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        darwin_export_sdk__476_v0 
    fi
    env_var_set__121_v0 "step_total" "9"
    __status=$?
    get_source_root__396_v0 
    local ret_get_source_root396_v0__65_22="${ret_get_source_root396_v0}"
    dir_create__47_v0 "${ret_get_source_root396_v0__65_22}"
    __status=$?
    dir_create__47_v0 "${cache_root_2835}/nix-deps/lib/pkgconfig"
    __status=$?
    build_openssl__424_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_boost__455_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_nlohmann_json__444_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_lowdown__435_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__463_v0 "libbrotlicommon" "c/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__463_v0 "libsodium" "src/libsodium/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__463_v0 "libeditline" "include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__463_v0 "libarchive" "libarchive"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
    build_nix__474_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix477_v0=''
        return "${__status}"
    fi
}

is_nix_installed__479_v0() {
    env_var_test__119_v0 "nosystem"
    local ret_env_var_test119_v0__24_8="${ret_env_var_test119_v0}"
    if [ "${ret_env_var_test119_v0__24_8}" != 0 ]; then
        ret_is_nix_installed479_v0=0
        return 0
    fi
    dir_exists__41_v0 "/nix/store"
    local ret_dir_exists41_v0__29_8="${ret_dir_exists41_v0}"
    if [ "${ret_dir_exists41_v0__29_8}" != 0 ]; then
        ret_is_nix_installed479_v0=1
        return 0
    fi
    ret_is_nix_installed479_v0=0
    return 0
}

get_nix__480_v0() {
    get_cache_root__200_v0 
    local cache_root_2817="${ret_get_cache_root200_v0}"
    get_osname__195_v0 
    local osname_2818="${ret_get_osname195_v0}"
    get_system__197_v0 
    local system_2822="${ret_get_system197_v0}"
    local nix_path_2823="${cache_root_2817}/nix-static"
    local fakedir_path_2824="${cache_root_2817}/nix-deps/lib/libfakedir.dylib"
    enter_alt_buffer__175_v0 
    set_title__174_v0 "Building Nix..."
    trap "teardown__177_v0; exit 1" SIGKILL SIGTERM SIGINT SIGABRT
    __status=$?
    if [ "$([ "_${osname_2818}" != "_Darwin" ]; echo $?)" != 0 ]; then
        file_exists__42_v0 "${fakedir_path_2824}"
        local ret_file_exists42_v0__59_16="${ret_file_exists42_v0}"
        if [ "$(( ! ret_file_exists42_v0__59_16 ))" != 0 ]; then
            dir_create__47_v0 "${cache_root_2817}/nix-deps/lib"
            __status=$?
            pull_binary__335_v0 "libfakedir.dylib" "${fakedir_path_2824}"
            __status=$?
            if [ "${__status}" != 0 ]; then
                teardown__177_v0 1
                ret_get_nix480_v0=''
                return 1
            fi
        fi
        get_self__182_v0 
        local ret_get_self182_v0__68_43="${ret_get_self182_v0}"
        exists_newer__180_v0 "${fakedir_path_2824}" "${ret_get_self182_v0__68_43}"
        local ret_exists_newer180_v0__68_16="${ret_exists_newer180_v0}"
        if [ "$(( ! ret_exists_newer180_v0__68_16 ))" != 0 ]; then
            pull_binary__335_v0 "libfakedir.dylib" "${fakedir_path_2824}"
            __status=$?
        fi
    fi
    file_exists__42_v0 "${nix_path_2823}"
    local ret_file_exists42_v0__73_8="${ret_file_exists42_v0}"
    if [ "${ret_file_exists42_v0__73_8}" != 0 ]; then
        teardown__177_v0 0
        ret_get_nix480_v0=0
        return 0
    fi
    env_var_test__119_v0 "nobins"
    local ret_env_var_test119_v0__78_8="${ret_env_var_test119_v0}"
    if [ "${ret_env_var_test119_v0__78_8}" != 0 ]; then
        try_build_nix__477_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__177_v0 1
            ret_get_nix480_v0=''
            return 1
        fi
    fi
    pull_binary__335_v0 "nix.${system_2822}" "${nix_path_2823}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        try_build_nix__477_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__177_v0 1
            ret_get_nix480_v0=''
            return 1
        fi
    fi
    chmod +x ${nix_path_2823}
    __status=$?
    teardown__177_v0 0
    ret_get_nix480_v0=0
    return 0
}

migrate_nix_store__481_v0() {
    get_nix_root__199_v0 
    local ret_get_nix_root199_v0__107_36="${ret_get_nix_root199_v0}"
    local command_66
    command_66="$(readlink -f ${ret_get_nix_root199_v0__107_36})"
    __status=$?
    nix_root_2816="${command_66}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        get_nix_root__199_v0 
        nix_root_2816="${ret_get_nix_root199_v0}"
    fi
    dir_exists__41_v0 "${nix_root_2816}/nix/store"
    local ret_dir_exists41_v0__112_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__112_12 ))" != 0 ]; then
        ret_migrate_nix_store481_v0=0
        return 0
    fi
    >&2 echo "Migrating Nix store to system-wide install..."
    __status=$?
    nix --extra-experimental-features nix-command copy --from ${nix_root_2816} --all --no-check-sigs
    __status=$?
    if [ "$(( __status == 0 ))" != 0 ]; then
        chmod -R +wx ${nix_root_2816} && rm -rf ${nix_root_2816}
        __status=$?
    fi
}

unpack_channels__482_v0() {
    get_repo_root__201_v0 
    local repo_root_2808="${ret_get_repo_root201_v0}"
    get_self__182_v0 
    local ret_get_self182_v0__128_52="${ret_get_self182_v0}"
    exists_newer__180_v0 "${repo_root_2808}/.nixie/channels" "${ret_get_self182_v0__128_52}"
    local ret_exists_newer180_v0__128_8="${ret_exists_newer180_v0}"
    if [ "${ret_exists_newer180_v0__128_8}" != 0 ]; then
        env_var_get__122_v0 "NIX_PATH"
        __status=$?
        local __NIX_PATH_2815="${ret_env_var_get122_v0}"
        env_var_set__121_v0 "NIX_PATH" "${repo_root_2808}/.nixie/channels:${__NIX_PATH_2815}"
        __status=$?
        export NIX_PATH
        __status=$?
        ret_unpack_channels482_v0=0
        return 0
    fi
    echo "Unpacking Nix channels, hang tight..."
    dir_create__47_v0 "${repo_root_2808}/.nixie"
    __status=$?
    untar__184_v0 "-C ${repo_root_2808}/.nixie channels" 0
    __status=$?
    if [ "${__status}" != 0 ]; then
        mkdir ${repo_root_2808}/.nixie/channels
        __status=$?
    fi
}

populate_extras__483_v0() {
    local args_2798=()
    env_var_get__122_v0 "EXTRA_FEATURES"
    __status=$?
    local __EXTRA_FEATURES_2799="${ret_env_var_get122_v0}"
    env_var_get__122_v0 "EXTRA_SUBSTITUTERS"
    __status=$?
    local __EXTRA_SUBSTITUTERS_2800="${ret_env_var_get122_v0}"
    env_var_get__122_v0 "EXTRA_TRUSTED_PUBLIC_KEYS"
    __status=$?
    local __EXTRA_TRUSTED_PUBLIC_KEYS_2801="${ret_env_var_get122_v0}"
    get_nix_root__199_v0 
    local nix_root_2802="${ret_get_nix_root199_v0}"
    if [ "$([ "_${__EXTRA_FEATURES_2799}" == "_" ]; echo $?)" != 0 ]; then
        args_2798+=("--extra-experimental-features" "${__EXTRA_FEATURES_2799}")
    fi
    if [ "$([ "_${__EXTRA_SUBSTITUTERS_2800}" == "_" ]; echo $?)" != 0 ]; then
        args_2798+=("--extra-substituters" "${__EXTRA_SUBSTITUTERS_2800}")
    fi
    if [ "$([ "_${__EXTRA_TRUSTED_PUBLIC_KEYS_2801}" == "_" ]; echo $?)" != 0 ]; then
        args_2798+=("--extra-trusted-public-keys" "${__EXTRA_TRUSTED_PUBLIC_KEYS_2801}")
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__164_8="${ret_get_osname195_v0}"
    is_nix_installed__479_v0 
    local ret_is_nix_installed479_v0__164_41="${ret_is_nix_installed479_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__164_8}" == "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed479_v0__164_41 )) ))" != 0 ]; then
        local command_72
        command_72="$(readlink -f ${nix_root_2802})"
        __status=$?
        args_2798+=("--store" "${command_72}")
    fi
    ret_populate_extras483_v0=("${args_2798[@]}")
    return 0
}

launch_darwin_workaround__484_v0() {
    local name_2909="${1}"
    local nix_path_2910="${2}"
    local args_2911=("${!3}")
    get_cache_root__200_v0 
    local cache_root_2912="${ret_get_cache_root200_v0}"
    get_nix_root__199_v0 
    local nix_root_2913="${ret_get_nix_root199_v0}"
    local fakedir_path_2914="${cache_root_2912}/nix-deps/lib/libfakedir.dylib"
    env_var_set__121_v0 "FAKEDIR_PATTERN" "/nix"
    __status=$?
    env_var_set__121_v0 "FAKEDIR_TARGET" "${nix_root_2913}/nix"
    __status=$?
    export FAKEDIR_PATTERN FAKEDIR_TARGET
    __status=$?
    _NIX_TEST_NO_SANDBOX=1             DYLD_INSERT_LIBRARIES="${fakedir_path_2914}"             DYLD_LIBRARY_PATH="${cache_root_2912}/nix-deps/lib"                 exec -a ${name_2909} "${nix_path_2910}" "${args_2911[@]}"
    __status=$?
}

launch_shell_command__485_v0() {
    local nix_path_2915="${1}"
    local cmd_2916="${2}"
    local extras_2917=("${!3}")
    local args_2918=("${!4}")
    get_repo_root__201_v0 
    local repo_root_2919="${ret_get_repo_root201_v0}"
    env_var_get__122_v0 "PWD"
    __status=$?
    local pwd_2920="${ret_env_var_get122_v0}"
    local name_2921="nix-shell"
    local shell_cmd_2922=("${repo_root_2919}/shell.nix" "--command" "${cmd_2916} ${args_2918[@]}")
    file_exists__42_v0 "${pwd_2920}/flake.nix"
    local ret_file_exists42_v0__213_8="${ret_file_exists42_v0}"
    if [ "${ret_file_exists42_v0__213_8}" != 0 ]; then
        name_2921="nix"
        local array_74=("develop" "${pwd_2920}" "-c" "${cmd_2916}")
        shell_cmd_2922=("${array_74[@]}" "${args_2918[@]}")
    else
        file_exists__42_v0 "${repo_root_2919}/flake.nix"
        local ret_file_exists42_v0__216_16="${ret_file_exists42_v0}"
        if [ "${ret_file_exists42_v0__216_16}" != 0 ]; then
            name_2921="nix"
            local array_76=("develop" "${repo_root_2919}" "-c" "${cmd_2916}")
            shell_cmd_2922=("${array_76[@]}" "${args_2918[@]}")
        else
            file_exists__42_v0 "${pwd_2920}/shell.nix"
            local ret_file_exists42_v0__219_16="${ret_file_exists42_v0}"
            if [ "${ret_file_exists42_v0__219_16}" != 0 ]; then
                shell_cmd_2922=("${pwd_2920}/shell.nix" "--command" "${cmd_2916} ${args_2918[@]}")
            fi
        fi
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__223_8="${ret_get_osname195_v0}"
    is_nix_installed__479_v0 
    local ret_is_nix_installed479_v0__223_41="${ret_is_nix_installed479_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__223_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed479_v0__223_41 )) ))" != 0 ]; then
        local array_add_79=("${extras_2917[@]}" "${shell_cmd_2922[@]}")
        launch_darwin_workaround__484_v0 "${name_2921}" "${nix_path_2915}" array_add_79[@]
    else
        exec -a ${name_2921} ${nix_path_2915} "${extras_2917[@]}" "${shell_cmd_2922[@]}"
        __status=$?
    fi
}

launch_nix_shebang__486_v0() {
    local nix_path_2898="${1}"
    local file_2899="${2}"
    local extras_2900=("${!3}")
    local args_2901=("${!4}")
    local shebang_2902=""
    i_2904=0;
    while IFS= read -r line_2903 || [ -n "$line_2903" ]; do
        if [ "$(( i_2904 == 1 ))" != 0 ]; then
            shebang_2902="${line_2903}"
            break
        fi
        (( i_2904++ )) || true
    done <"${file_2899}"
    starts_with__23_v0 "${shebang_2902}" "#"'!'""
    local ret_starts_with23_v0__250_12="${ret_starts_with23_v0}"
    if [ "$(( ! ret_starts_with23_v0__250_12 ))" != 0 ]; then
        ret_launch_nix_shebang486_v0=''
        return 0
    fi
    slice__25_v0 "${shebang_2902}" 2 0
    local ret_slice25_v0__252_27="${ret_slice25_v0}"
    split__5_v0 "${ret_slice25_v0__252_27}" " "
    local bang_args_2905=("${ret_split5_v0[@]}")
    array_shift__78_v0 "bang_args_2905"
    __status=$?
    local name_2906="${ret_array_shift78_v0}"
    i_2908=0;
    for arg_2907 in "${bang_args_2905[@]}"; do
        if [ "$([ "_${arg_2907}" != "_-i" ]; echo $?)" != 0 ]; then
            bang_args_2905["${i_2908}"]="--command"
            bang_args_2905["$(( i_2908 + 1 ))"]="${bang_args_2905[$(( i_2908 + 1 ))]} ${file_2899} ${args_2901[@]}"
            break
        fi
        (( i_2908++ )) || true
    done
    get_osname__195_v0 
    local ret_get_osname195_v0__264_8="${ret_get_osname195_v0}"
    is_nix_installed__479_v0 
    local ret_is_nix_installed479_v0__264_41="${ret_is_nix_installed479_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__264_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed479_v0__264_41 )) ))" != 0 ]; then
        local array_add_80=("${extras_2900[@]}" "${bang_args_2905[@]}")
        launch_darwin_workaround__484_v0 "${name_2906}" "${nix_path_2898}" array_add_80[@]
    else
        exec -a ${name_2906} ${nix_path_2898} "${extras_2900[@]}" "${bang_args_2905[@]}"
        __status=$?
    fi
}

launch_nix__487_v0() {
    local self_2793="${1}"
    local args_2794=("${!2}")
    get_cache_root__200_v0 
    local cache_root_2795="${ret_get_cache_root200_v0}"
    get_nix_root__199_v0 
    local nix_path_2797="${cache_root_2795}/nix-static"
    populate_extras__483_v0 
    local extras_2804=("${ret_populate_extras483_v0[@]}")
    split__5_v0 "${self_2793}" "/"
    local ret_split5_v0__281_33=("${ret_split5_v0[@]}")
    array_last__74_v0 ret_split5_v0__281_33[@]
    __status=$?
    local name_2807="${ret_array_last74_v0}"
    starts_with__23_v0 "${name_2807}" "nix-"
    local ret_starts_with23_v0__283_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__283_8}" != 0 ]; then
        unpack_channels__482_v0 
    fi
    is_nix_installed__479_v0 
    local ret_is_nix_installed479_v0__286_8="${ret_is_nix_installed479_v0}"
    if [ "${ret_is_nix_installed479_v0__286_8}" != 0 ]; then
        migrate_nix_store__481_v0 
        nix_path_2797="nix"
    else
        get_nix__480_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            bail__181_v0 "Failed to obtain Nix. Check your internet connection." 0
        fi
    fi
    export NIX_SSL_CERT_FILE
    __status=$?
    file_exists__42_v0 "${args_2794[0]}"
    local ret_file_exists42_v0__297_8="${ret_file_exists42_v0}"
    ends_with__24_v0 "${args_2794[0]}" ".nix"
    local ret_ends_with24_v0__297_37="${ret_ends_with24_v0}"
    if [ "$(( ret_file_exists42_v0__297_8 && $(( ! ret_ends_with24_v0__297_37 )) ))" != 0 ]; then
        local args_shebang_2897=("${args_2794[@]}")
        array_shift__78_v0 "args_shebang_2897"
        __status=$?
        launch_nix_shebang__486_v0 "${nix_path_2797}" "${args_2794[0]}" extras_2804[@] args_shebang_2897[@]
    fi
    starts_with__23_v0 "${name_2807}" "nix"
    local ret_starts_with23_v0__303_12="${ret_starts_with23_v0}"
    if [ "$(( ! ret_starts_with23_v0__303_12 ))" != 0 ]; then
        launch_shell_command__485_v0 "${nix_path_2797}" "${name_2807}" extras_2804[@] args_2794[@]
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__307_8="${ret_get_osname195_v0}"
    is_nix_installed__479_v0 
    local ret_is_nix_installed479_v0__307_41="${ret_is_nix_installed479_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__307_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed479_v0__307_41 )) ))" != 0 ]; then
        local array_add_81=("${extras_2804[@]}" "${args_2794[@]}")
        launch_darwin_workaround__484_v0 "${name_2807}" "${nix_path_2797}" array_add_81[@]
    else
        exec -a ${name_2807} ${nix_path_2797} "${extras_2804[@]}" "${args_2794[@]}"
        __status=$?
    fi
}

array_83=("tar" "gzip" "uname")
check_deps__185_v0 array_83[@]
__status=$?
if [ "${__status}" != 0 ]; then
    exit 1
fi
load_features__489_v0() {
    untar__184_v0 "features" 1
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "The resource archive is missing or malformed." 1
    fi
    local envfile_123="${ret_untar184_v0}"
    eval ${envfile_123}
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "The environment file in the resource archive is malformed." 1
    fi
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    env_var_get__122_v0 "SOURCE_DERIVATION"
    __status=$?
    env_var_get__122_v0 "NIX_BINS_DERIVATION"
    __status=$?
    env_var_get__122_v0 "EXTRA_FEATURES"
    __status=$?
    env_var_get__122_v0 "EXTRA_SUBSTITUTERS"
    __status=$?
    env_var_get__122_v0 "EXTRA_TRUSTED_PUBLIC_KEYS"
    __status=$?
    env_var_get__122_v0 "NIXIE_VERSION"
    __status=$?
}

declare -r cmdl_68=("$0" "$@")
args_7=("${cmdl_68[@]}")
load_features__489_v0 
catch_args__222_v0 "args_7"
array_shift__78_v0 "args_7"
__status=$?
self_280="${ret_array_shift78_v0}"
file_exists__42_v0 "/etc/pki/tls/certs/ca-bundle.crt"
ret_file_exists42_v0__68_5="${ret_file_exists42_v0}"
get_osname__195_v0 
ret_get_osname195_v0__70_5="${ret_get_osname195_v0}"
if [ "${ret_file_exists42_v0__68_5}" != 0 ]; then
    env_var_set__121_v0 "NIX_SSL_CERT_FILE" "/etc/pki/tls/certs/ca-bundle.crt"
    __status=$?
elif [ "$([ "_${ret_get_osname195_v0__70_5}" != "_Darwin" ]; echo $?)" != 0 ]; then
    env_var_set__121_v0 "NIX_SSL_CERT_FILE" "/etc/ssl/cert.pem"
    __status=$?
fi
launch_nix__487_v0 "${self_280}" args_7[@]
exit 0
cat <<DONOTPARSE

-----BEGIN ARCHIVE SECTION-----[?1049h
‹¬Š jÿ í}	|EöõÌ$™„@äâÌpš BÂ}J˜`€‚ ¢“LH$—™.q\Æ‰‹«ë±F]ˆÇÆ]P<	‡€âjÀY€¨Ãİ 	×üß«z=ÓÓ	xı~ÿÏÿè‚êªouõ«z¯Ş{UİÕéÉ³e;œe6;û	ÆÍSê4aÔ¸QŞ¼(7&1‘™Øÿ†à´;²Ë IöÿgHY˜™a¶ÎH1gÎÏH™7¥qÁÊksJŠŠ²‹sMy…ÙËlöş!¢Î¼ùÓæe¦fÎÏLÉ€zrifÆüy™)ÉÖôùÓÒR§[¯O¹‰Ÿœ7w~ÆôëtótKŠ º¢,»txNvN~ÁÊá%eK½U’S2Ro4g¦Î3%?;õªÄQÅ‰·-)(Î·4?¯4wdŞÒDûò¥+ÆO˜2'u¡uZêœyÊ‹òJF-+ÈM9j|îmÅÙ9ãFN³,ï¶„ÑË—ç.MX6/JM±Ş½Æê#F0êÚìÄ¦Æ†>")={¥Å–k+ûŸ³ÿìŞgó£FûÛbÂÈÄ‘Ì´R³ÿÿñ0r¼©ÈQPd›’8nüø		cÇŒ>aä˜Q£ÇÖäÿƒPX°$¼|nAÙğÜU ş§çÿqcÇ
[I6?rì¨D°¾Ä1#Ç€İÃqØÿ¨Ñ°$øß;ÿ;‹VÛ¨+Öƒjyyÿïÿ;—_}ÄX¤zÆÂ!q<‡P(µ >“‡.šÅhAZĞ‚´ -hAZĞ‚´ğ_xÿüw—áÆ_‚1bi cëùs Æz@<,1fµf¦,Ìì€@RÇ8@1X­ÛJ‡¯šš^#Uœr­”t¬\	­V»Ã¹Ä~Ez]èIÎÉ‡%ÅõF¢è½¾  •äåÙm{{zîÑtëô¢Tb°Zsì²‚â¥Wè_Ñ[/ùc9èÚÑs¯((Î…næ•t@oåX‘ÆI>¬»Ê¸ã¸º9ds¦Ù:}îœy™~ã®_ÂzŠ:*²Z—–8üúÙ1½r^Qå?×ïú‚b‡­¬´Änë^ù4Q/ˆ 6ül>'Ò¯ ¿¬=Ÿ4%EE%Åş|¶§·<N©²¾ µÏ%v{;¹ùpùJÕ8ü=äÓÂé¤¥Î¹>%9UÖjJüûùğ@%­ÎBŒQ•˜o·•ÙGĞSÒée%·ÙröKóG¬,°][f[^`[1âJÏ“A½ËÃ©}Øö(Â¦ùŒÕ„œ±Íñ‹ûy¹ª†0ÖI1TS)Î‚èR”wöƒá=ÑAy/jÇrsúoFõÒm—>¼ıîFb_¼<÷ÇÕ“ç…šıhâ?üÁèx¢%t$- ¯á´—¡0Î[ewØŠ†OSJb0Ñi¼‰±|Hã	#ßÿa¾ÅõµyùFó|sæ¼ôò)½PXaëo^,US.kø\¬ÅµÛ²¾!ìÁ€K©üÄxbœHuíµTŒ…«Ò\	pâßxâY~bœÄOŒŸ½şlØºD 9{½'lúsùu#ÂÖ÷à¹©“°â9·e8^º'ÍåqOÁì„=+¢ ¤¹Î¦¹¹ º±®Gdı¿İ-UcRG0¶EšØàşb´şø0¬ô»Å®İ)‰ÇÍoà¨¤U©„‡Å2sÕ·sï_ª+ĞâÚçşù«h/ë“Z59ÈR±¯åU”0¤İ¯_‹äÍ>¿Óhöì1{Şj~X›…’¨DóogìU´¶Wğà†ô÷·8ıÎ=”‹ğU0¿Ä³î¯¡öŞ€M $KÅãÍæÅæ[Ì·š­·ìvgAE÷$<,‡C^Xl²o¼æ¥§ºÎZ\ÜÑBÖ(»PÌNØ·ÜØĞÜ
,®/Ò\çİ¸<Â66úœ6[ç7ş^zû†yé½>ÌG¯Gª´wvüeÕ§; 
òEzÀÜç3»å„êäñ0¼}{ØØ¢a\ôº²Xö'ĞıWq -®/İ3àLâÛØÀNKUïëA‡€dZ%¨’Ç1Õ£ï0¡}P¹;ïèŞİ ¤¹ “?¸y÷cÓª¦¼½.œpÁÑòo¬PnÜ™C0Ûª`š[6‡o¼ûå¡¨>SÖÁ$:«jòø4éG~=^÷G8Õ¼÷jü­ªàïÜ0yCÕüŸáÏßuC½üÚ¿ÁC½üXîãïóåğçˆï€¿Š‚¿O†pş6•µçï¥!WáÏ²ö$¬‰ ‡g],•†±H.KiJ«z£é‚Çã×wKœHó‡pãì-Ósí,½3Vá¸¡Êì©hÓİyuïÃK¥ªOçÕJ~€}‹k¯{S¶P3F49)¥)lı=\®‡-k÷`¯ˆÍ½ë8iàot|êÚ½G/ ÍmXB]Âm¼Ï³«¸©ß2TÕ{|œª|{@œ89»>±2 “¢ëV{<wÛ5ÜX¯$¯s\^öÊË¢–—{÷5BXï_ôx*.€Ç|»ãHÏJª!ä°?NhhÑ†ç$>ŒŸCé{×±ò)!;"lİT~)oÁİÇ…ßO1
ù‡T´JUI'’]g¥½a¾Å
§*..˜Re˜aöÀ‰]ñ?$OØuW÷ÔœF‹ë}Kü'–
)¬âzlÆõë‡s‡,®Sgwé×Vİ(UÓW­” À+a/&$W…†ÍÎy{æÃ‹çm‹ç§ÛRqY_¶ÚµËRuûåª•Ô} JÏlW›Ê¤„½œVÕ»kJ•]šsvæ†ˆë ,3Ø3;ç_ &qp9¹ª÷eÁ%(ˆ¢‚ÔŠƒ¥b×ÅÔŠÁÛ_L›°Ó¹y}ÃÊOx®GW ¼¸’X\»Ü!×pg½JİI\qPòƒ/ÃÙÊÎa£pƒ-“f79-şª*uƒìkp’‰ºÆ;V®ÌËHÙıÂENgßH/Çv÷+ƒ°É¤ŠË±vC¢§ù×'ß6%»ö¦ºZSÏS:º~*%ñøÛéaáÉ][àÚu†`qzX×´I§à˜<éhjÅ®¦ÙŸZ&œ[=»+Æq£ÙÕh®hj…ñJ‹ß›R:Ãßföì´Ä·¥Åï³Tìlã´ùıÎõÜÊŞ±3«FwqÏu-¾®¨¶¦MøÄùUÚ„]aëƒ›o @âÛN´]tè/øúl ûƒªı Ê4×úí\ÊU¤º>´¸~Lu]ãx9Q6Ğ±s‰g¹?Ä•‚kïÔ
ôM›Pr®}oâìî~q „õÆ¶FÙ’Á‡<6H¤¯Ãéä°—ùI/ ²Şãœl{ù½µmú1æL°TòY\¡-U6òNş<Íu4­r=v3­²
;í6Ä‚o Ÿ=Š³œ¥4AÆ=¢òÑÙ o£³¨IWß<¿ .M|ò}ÛÖŠ®*òş'ñì-'j(×koâ›6·œ@Ö«Õş¤·*ÁçZ`2Y“
3FÕ”ë“¸Oqıè^âàb@‡¶»+Ô]é°Ï¡–O ÜĞœÜE®å—œsÃk€pşŒ	>3ˆS™¸EgD¢Ç¯ôD"\ç>ÔÜ¤èÿó\˜qùq™÷Ë|n/“LÌä¾¿Íãip¿|6x%×‘Ä rË‰{¹Ì’|úÚåú f£TX,Vºe*öñ[wöpß¾S¼ë—%¾=ÛÕ’êúÔŠêÚUJ¡Šë0‡Xå]YÓÓ\³g£!¾êšê:s<VËuÀÎ€4I|êæjƒvÒ*g7º/\Ä† Ö;XKÏS-ô:^? 1àÀ=p…]ıEÚĞ_?»Ì'!,|¶¿˜ş”k±r¿şsëkD‡R:gv]»‹ãbYŸÀ“ªñ¬kp‹_ŸÙ°øªt<˜Å“ÇKyb+‹/ª‹wÖ†ÅßYê2\V·ÃÀåñ)Àe4ôÖŞçvã­c¶¥j}8·:0çª”pH÷[¶ÇĞ=& †WøVE[ÜŠ®¼Ü¢Oi¬ØitÍnhµTBí*‹Ñâš½ŒØd®¸|9ìÁ†³»M°t2ît„c£Ø99ƒš#Hµ/»o8ÊÓÙËÀ¤’¹b»$»ÂİBØ<šØéü~Üz&]+Ïç‡İø‚…æUw/®i;\ïÑ€,ªk?…í9ËU=Ï‹&lkœ1ù´AhBuôjˆŞN“‚Ş¦s^zç¼ô¾2=×T×Ç©®ÓfXVM™TİÅp¹Â£¨‡Ôã/ĞoÜì¬B ß¸ûCz¸üLêñXgÓ$ İÃägVWÖï¿Oì‹U°÷–p÷Q_™»}±*îTöï:`Vğw3vâşØ_ÂŸéŒæ³2Éœ¿?õ%ş’û3ù;4Qğ§Sò·í´ÌŸäåïÛ¾WáÏGïn¢÷÷¾
z6/½e^zı<z#‰Ş%½”32½¥}dz3ûşùÿk©Kß_"ÿÚıä¿x‚Éùc10 }ûĞ Ü…´·÷Q€Úßñ9ELs&ˆéàw}¼<^vgŸöÍ*î{z6¿ugõùYóıïÇú}•ôş  ÿg/}ÖççÏ7É®İf×{f×'0×˜]õuĞ’ûåŞ(Ö‹j±^äbıÖ_¬ß»SPˆõ{÷m?¢ZËÕú|²ë”ÙuØıN/’ì $kï&)•|÷ ğ›ú8ÅMŸÏÇ‰û¤Î½i8…kö7‡¸Öhì©Ğ¾‡°¢(/ìÅ×}Hk_M<r÷†ËÙ5ÙÕâ¿àpßÑ³Cÿì•gªë]®¦g„š†º—öÂ…"Jçìî$g;ú_v$ı€ËÒ·`Ò@uÔâî *;°¸v¢Ü>ìIrûnİƒ{u<¹·_ëBZÕ˜—ÇŠ‡^ßÊÌ£;¤…«{I/¡1çÜïõsë-»ıü9.wÌ\ÿŠÇ
ıûsObä¬{^‹ì½@ûz÷’µïî~Ú×Ñ|Óo¬p7({ehá‹?’{ÊaLÏ«Í7…üsŒèà¥¨¹—i–riæ´¡·gñkaO¹¯÷PYx2»Òz¯ˆè?ŞC¡oéÿá’LCºGÜ{ğÇ˜XëNUÚàôÅBs&¬—.¦U]Ä[ù{\a2±µn-²]¥¡~|ê—ü;´‡by¦0©¤ÖOò?£0‰­ÿñÎ÷ñ1D×ãŞ£^ö]A>³GùÜ£O–Ÿ|G{åsKÌOÊíÿ0®&±Ó×ƒ&®'ÿ=+Êí®dÊp“í~+W”«®(Ã•+ÊpßŠ2üê+Êñ²Œ¸¸ëˆù›¿ù{šÁOÂj1&šl]ÂMŒæÎ¨ó Ÿ3
ç«ÅÃÌç‹şy•çŸòè Å¿Áı¿ûX”ohÎî–À5ˆ~¸N¢ÚçU…U'eï£öa$õjÒØ¥2ÈêŸôxÙÒ(ŸÿÃ†gŠ†ÃOúù¿“íıßb¹õïÑÿEıLÿçí7/³l^›…yôz±ªfnTÉ¨c»À¦®‰Îá?îW";j¬ºCùÎÅŞİ©–oÖIÎf|³¿|{4+äû@qØ	i$G^I¾Êõ­ÿ#ö{ºÙk¿wFz×ÿ?kıOôvF(×ÿ>z×{é=ñÖÿ	¸şøEëÿû¯ÿ›ı×ÿoÈ¢jÂm“W_«×»c•ë‡ÇGˆõÃ?»+üUù‰+¯ª»)„³à„wıPßİ»~ø}wn²‹b¯º~˜ÔíÊëoŸßEåâ÷¿Ş7Â”~|¸˜Ò#ºË&å~Ûİ~¾QÕm|räş´+>ÌEişÅ-›—ëX—ûR7yú¿ï÷S}å~7:#Oº}Ï‘Ê»ªï÷Ãt¿Ÿ
‹ÇÊ k_ï­:tuuµÀ'ºoÜ½ygŸVw§5÷°®ŠÁøñ[L¿V²ØÛÙş¢³gú¨ï¢ÃÊ»èÂññMrÇòå^êŸ|Õ{ÖÌ;şLßÁª)åp‹îşGW¬ø-wş·üVcGÏ°V†{ÇÁü-÷%p8tr`w%†4m]yçÇ÷ù)IG…ûíÇÉë¹o‡	‰FwU¬œÎ+Ös÷u•et9¼ızÎw?öÔ0aî‡Â½şù~ì®pÙÚ_ÿ‰û1ßúpÎ0ºÿ	÷zÖQß(Ö‡	áòškIxëC™¿ âo\¸‚¿-ø»5\æ¯¯š?ùú}CÅõçÂ×¬¹è"_ÿEXGòñúÃµC…€^Shã7^ø]˜,¡Ã®ì}ó0˜â†Šùga˜Â :}M‹¤ËÂË}ÛÅ»ªÖÑªî*÷‹ŞåØ›CÄx|ßEaQO——c0"²4¾u7vù%÷‹³?Li÷|2ZsWtQÈ|¬Ü=¬Lqµ$WÎşĞıL2‡>xÉ]~ş|îÓßcñbxºuQ>ÏùJÖß¯:{W¯g;·SàvÏ[Á¼—Šà4nÀıo<Şÿvö’†ûÙ¯ˆ—oÒ\çÓÄıìáÎÄÇ|¬~çŸ¾Ÿ½R{H`¦²½óÇÚ··9”Úûî‚İ}A{şÏ“ùp=‰4>Ã÷î{Ñ®“ÿsåIr“eXıÙĞ›ôóbƒ´/)Nh_i¨H‹C½û›Íh÷ÿ[wF(ÇÂÙ	‡ê‰PñL£="ÿ¢C?¸åûcß]ƒë¿PÿÛoû^û¿†ì¿“Òş…<İ{:‘bœsŞ‰èè}™Şû|snÌ_@Ş¯ânÈ+Qq¢!ŠVÃy!Îwç…E!üÒçy/ù–‚ß~Š˜*NZ,.gÌ	£[Rwnç{RIàÙñm”~|oj_Ø‚†°ø¸‰I©¶ìKÙÏøş²³úU|MøëL­½³_ [ÿ”UÜYËÂÖ}Æø³òæ(1Ÿ¤ÁúÌ³'y’­6¬b'œz_ D?]åÜï> †›—)p{Vî­huMÕG¹sUªë›äÊ¢wS+ŞjMs¹İ¹Áx÷Óf©hj±Äï±¸¾â®ş‹4×¿İ÷ }ZÕ0=Ö¶T¬Ìß@]ûóçxÃ¶n¹Gì|U:·»ˆ²õKD™g~Ã‰xß&ô¹Òù®¥bo+ç#à~Z–¸{ª‡Ï1îIÁ|^mŠôÍ«a–*Ûaå”ºÛÈßÏQ¯ò©ü ÜS6ˆ½Âz<(vßØ€IeÀ=‘ŠõÁş‹kÛÃ¸Wläï=:4¼êwQo¢F¸ÍPhÙ>-Ãœ‘š2oJªkF—°ğ€ù0Ræ°ø@pf·`íÊ©î‘×ÓÕØ\ECW·Şè'àTÜ´?ßàH@\+ Ü}$HUñ8’[‚§«J»â,òfĞÙ9¢,m¯Ê #_…`Gº¦@g˜ñ%½kªË0Ğ²İšiÎ˜™’	N4»r^ß…_Ÿ4Ÿ¯—hĞ'üe¤Çz»ö/I‡vŞÌëñ5Ô(Mİ·mÆÏ¿ÏªXó•‘Í®Ê(94W%4Xv6éİz5[_Ï^<lİSp…™^JâÙ}ëqÃ¾õïR®y€z?ßunV¥áÇë]ÉgXªgïì	§«gUş|
ª’;ô_¨}ÎÃTvËZğÇ
É®mØBó›ÊşŠz¯b½F^¯’7nKÙëâ¹æÿòuÇ×EÑkT¿£Ox5Jvp7²Tìí¹r§±’+İ\«RbÜ2yRÂ’/†mlpíL–¦æÀ²ø#–x¨’w±â²'lã®°äSÒAKÎY¸¶–ïx¯9ÃÏV¾4€@RØÆ½a)ï[rŞ†
›E…2‹´+MúÆ"}œºD$œÊ”ßõÇY{S)L ÂsÊ1˜ö¿-•Â:*¹­Ğ¾õl×	w1\ĞEb©ÜÆw¬Á#l@BB¹+;OìæÛ­ng¥}Ä+ŞY`˜íú§˜Ô,®ÀFş‘Ûè±®~6ú£ß/á°ßLsmk€SŞ÷EÊ×è=&gòÉz“3
4Ng™"A]ç·Ûñºf½Å³ßµË"1£±ia/¥l«h	[w=l›)lİa¹ü</ÿJ.?"—_àåÇäòOåò‹W s‰—7ÉåŸÈå—yù—rùÇr¹‡—ÏÒS¹YÏËCGòâ­rõg!“Z±×˜ºör_ÁÄghæ7ù»RËeóÆ~MØ=øî‰Íâ‚6ÕÙåËOÜ/ÎœWŸYÜ¼Š/¨‹Sš³ ø¢ºxxs*_RG7„âËªâ}\|şânñ4X¦`×ÿáãäj°T…êÁ{oF]ÀlÅN}J¢'¯zZùš	—B×az9Ä‡©'Ä1dZùä	 YÙgH]ëáäÍ;ø¸wOõì›½Şãì„½Ù§Ã—æâS`Š“ƒB(õèŒ79;§Vx¤ÙUwyîú´ÊæÜoJ­Xó–›9†bÚÂñ˜¶2Ç5˜2æèoÁ—…¦èY8s~¸_½mŸ×p©9—¹úÁ´P„€E×úíœ=Ã[¸‰íşRROÂ)®ÓtŸê½E­Ü†½Àw[ñ/¦í]7O³Ù9ß¦‘œóÖD{İL5ëåšçğİ6×¨”õÇÓÓ\wS+aªXß€/£@UGTâ¡j‹+¹{xjer¤ÑR±Ë'ßYªÖ£õY\ÓÃÅ³ÑÊq›gø_NÅØ7q	"ËÓâ2Œrc€³½œÜ÷>rÆíFNn›8â}†á±È1q_ê:+Øp÷Ña¸İ}nç:•Û!Öã›Ãë{à»FSàêy¯U¬¾'€ƒ{…ÿz\öĞ£ÛtÖÄ÷kPx›du¿Å¼ë8§÷ü£tşi¿óñ¿ƒÎ¯GêA'Cñø=?¶ğãüx‘/ó#¾$ï¤ãG?ò£‘Cø1”»ğc8?vãÇ~ŒâÇ~ìÉ½ù±/?šø±??äÇÁüÇCøq?çÇ~É£ùq,?çÇ‰ü8™¯ãÇ$~œÆÉü8ƒ-ü8‹Óøq?¦óc?fòãü¸ñãb~¼•³øq	?æòc?æóãmüXÈÅüXÊeüèàÇåü¸’Wóã~ü?–óãİü¸ïáÇüx/?ŞÇ÷ócugñ÷DYp/¯»’S¦ÍŸéEéæÌÌ”Œ9^,–cìÆì²‚ì%…6»IUÑ„ŸGó¯l*rÚ¦%6“İæòë.Í^b/)t:l¦ÒlG¾]A¥‘¢ìU¦âq‘Éî\šJòTtÀÍôÇ·˜˜3æ¤Î™9Ñ”™_`7-qæšVdÛM9%ÅyKe6€ü§Ã”k[â\j*²ÙíÙKmØvÔ1b8Á&²ä›Ò’­©sæ¥ddZÓRåU·ZªSTb"ÿİIoúû°ÅŸ¨àûÔÙ’^êÚÉ \ õãŸ¦aşIÆÎô·]™üÍN(É>¤?¡B¿š®c†R šedºê`fh€…dyÓ7„0ÉÔ	ÊàŞ ©“Ğ&š:3©´c]˜”º’Î¤ê®L— +¨¦nLWÚéë»C×#€n“Â#™®îT#™”u¢™®¦Š¦@§'c¦^€{1©¼7Ó%õaúò>P·´Û—ékû2ÖÒ—é²b™Ôçá®²ÚÄtMı˜”ÕŸéÃ@~ØUÿ´IZĞ‚´ -há7„ğr‰R¥zJ”PHi¥FJƒ)¡´¥¡”v¦´¥a”†SÚ•Òn”v§4‚ÒHJ£(¦4†Ò”ö¤´¥½)íCi_Jc)5QÚÒş” t ¥ƒ(Lé5”ÆQOéJ‡R:ŒÒk)NéJ(M¤t$¥£(MéJÇR:Òñ”N t"¥“(LéJ¯£t*¥I”š)FétJ“)M¡t¥3)µPšJé,J¯§4ÒÙ”Î¡t.¥ÕáâÜåqm!,Ë#««À²>Ô–åŞ]`y²ËüÔ–Ç=)B`Y?«	ËzdŠXÖ×RÂò86–õ8<J`Yÿj	ËúÍ¢–õ)‹°¬§¢áp&ëY=aYß’z,Ë±œ°,ÏFÂò8˜z
,G9aY_šËz“ŞK`ÙNj	Ëö"N„3Y“ú,Ûm=aÙ~“ú
,Û_-aÙ~Ãc–õ$‹°¬õ„e=I2	,ëuaY¿kû	,ëwze½ °¬é„e;­%,ÛkaÙN
,û±RÂ²4–ıBÂ e{¬&,ÛYø`e»Ï",Ûc#aÙ?%]#°ì§ê	Ëş*!NàôÙm.Ó‚´ -hAZĞÂO\[â·´ª%‘*¿û%o@Ä¨®·)~ßOã5:ˆ°†•àCÊ„¸âŸ!¾ñÄVˆQ“¦AÌ‡¸â=†øÄ­ßxâu:&E@L€˜1âˆË!Şñˆ[!î…è†¨Ó3É1bÄtˆ‹!B¼b5Ä ¾	ñ]ˆ_@üâyˆ!&ƒ˜qÄë!†h`R8Ä'C¼bÄÕÿñˆ¯Cüâ¿!‚ …h¸âm×@¼â&ˆÛ!¾ñ3ˆ-ƒğnVkNş2»c™57»lEA1–,Ym++ÁLÎÊlk¶Ã¶²ÀÈîÈÎY†µ­yÙ…ş%KÙe¹¢¨¬0'Û…^XºJ‹ıÏûÎæ®*Ìµ.µ9¬EÙKmÖâì"›\*JrJœÅĞ“ìœ›İÎàªÜ‚2Lò
³—r\T’‹IÉ
`#§°¤Ø–WPhSd³Ø¡,·°¤ÔÕrKË
ŠyÌj[™“Ÿ]¼Ô–›íÈFdËYnÃyÏMâåy¼ÊAC"§l OÎ+³Q¤ÿ¦Î™›œ2v4C³ —»Ãd˜³"—§¶âåÌZHÜ/G¬…µWâeµÛlxÆî×D‘­ä
é2."à…EËò
ò`hEÏğˆ¥˜Bßå¸!Œ;µ+±¬´ÚK³±¥ü2[v®µÈ	:aÍµÁğ•¬Rã‡-Õe…%9ËÔeÎbQŠEâ(x”sØ±2[QÉrqZf!RqZäVZ‹KeDù"Î·])i DÉ_VˆòìJ\–ë,e²&3Y‡EåÆÕ¶«¬*¦Öv”9QÅ¡£Îâ\[¡MäD5‘b-'ş
R±İ›•?Î(YÙ»FîËk%8n€#ÓeçÚrY0H+LÏâ˜Õ[àP;C1w-\¦0!gÔ„Õ&JĞVÓå³‰^ÃX gå±p²©¿ÃVl+c%@k
”TÃ¿Nak%n÷Hp*ÏÃË†C%aÏHÂ…
“6S/)Œb”7ÅÃŞ_ÃX€×¤”rØ>‰kä‰ŒæKI;çÀ5³‘?€¿­Ÿ‹‘‡õaÚËSP^>I'Â¡<ëî€²†T¨’ß£“æ=(­†C/ëU]û@Çmï8œ©‰MÍÀË/l—£\+ôÜnªôĞÂ l&›¯Ãîë±Â3p¦:
[úñŞ	óyM¯0Ÿ¨Ò4¯ƒô¿@Z³°¹d¼Ì,qÍıJk§ã€%!ñsz^Za`z²¯ô>“øNÏ-bƒ®Ÿ	ÍÚØŸ\ñ_†’&ìMõõJY½m à¨AMƒ¥<;s¬=…;Ùì
å;©øE¨T}’œ,ŒÂ.ÄêÏ€ˆ„?À«> œMEò×¡ôqŒ÷ØÙ»P±˜m@ugXòãırXycğ¬RÊc'$ğì¯ºBvBW´Œ= çgŸÕ—²·ôeìuƒİàµ³Çœì ]XÂ"‹VYY34_~ØNØ0Ùµ<Ûtö5¾Ñ„ƒØÔ€Z>È“o•¯9„zbÍÎÍw‡^ÒVœS ÆúY 4Ôh`û¹•6ròÕ‹±X…èÊì6«=ß¶ì‡½äÈÉ·‚3/eA|0le † ŞxZöVt%
…Á‹*Ígæ`àLm7”t¸îm9«62½¤p¹Mv8VVn\QVà°q—Í4ä÷0ºNVöj ïzA!\Ãöb.ÏYXÈ3v|‡,°ówpØÇE¬:Ì‚û[P)k
*ƒa5âV9DíFÈãèìE7ÕØ©^Ÿnj’š¤z]y`½ÎŞ %e•¦7éÒÓ«%üiVV­T/UKIééYp2«AW
…¥xªÿkÀSIIé¥YåRzii)³ÊõõAµÁ&ş(ò.Xªt‘|ßmş/Â&ú@ò„³Äƒp¶•p½Øà`äë	#ÜB¸qï{¿:£ÀÕ„Ã	×îA¸pÂ„‡n$œH¸‰ğ$Â-„“	3±ÂÒ	‡^DØD8‡páe„“/'œNøw„³ÿp)áÓFû“Ì?á§dş	?+óOø%™Â2ÿ„ß•ù'ü‰Ì?áã2ÿbˆ”ù'|VæŸğ%™ÂÁÁÄ?áhÂé„Î"<†p)á$Â´ÅR	WO¸–ğ­„ë	n ¼œp#áõ„›Wn!ü0a–Bò&N¸°‰ğß	'~MæŸğ>™ÂÉün’ù'Ü,óO¸MæŸpPñO8šp=aáÂCû¾+=JÆk"cÚA˜)ãudÃŒÌûÑåN„„qß¿ù+ö×ßoCœ@ß™',ö×K¸°™p-}H=M¦'6¢ØÍ„ë	ûƒŒ­$LËì^™Øøc®¦8o–1õ÷eÂáÔş[2}±ÑÌ>ûCô¾&,öÏ@oäö_’û+6.Yˆ$°Øßa¬a±¿ÃØpÂõ„'fÔşÓxº\ŸğbÂ$ïe„Ã©ıå„ÓéËƒk	Ë_"¼Ÿp)Ç#r{bcm’Û#y×N ï¿!·Gü ÜBòşŒ0mĞ³n"|^¦7ˆôKGò1‘~n!<ˆ°Øïcla±ú+×'ş2gQÿrWS{·ËçI^w.%yş°Øoel#aõÿ/„Åş&c/Ê˜Úß!óC× L/.°O	×Óõn¹?„OËõIŞøƒhY²=ê©âÅIç%:ß—Î7Ñõc	W“½˜	§ÓxÍ"œ@¿ø¸ˆèYˆ^átÂ…T?\lÌ³»	g‰Vö LOl¼³-„ıÊìNÂI´~xŸ°I¼XÂ¦O`¥-Ú_HíŸÑóçOŞGWø77J®Â}U8A…§«p†
g«p©
ß¥Âªğf®Wá—U¸A…÷©ğ{*ü©
£Âß©ğ¾¬Â¡ş8B…{ªğ ¡ÂTx¦
ÏQá*œ¯ÂN^§Â÷©ğF~L…ŸRá:Ş¦Â¯«ğş@…¨ğW*Ü¬Â§T¸M…CUã£ÂıTx¼
§©p–
/Wá5*|
? ÂO¨ğ_UøEŞ¡ÂTø
©Â'Tøœ
ùã0Qá~*¯Â#Ux’
ÏPát^¤ÂKT¸P…W¨°‹Ö<•¨ë8Ÿã=?ÿQƒãñ¨÷è‹ şâC¸ÎÅ{œï!>Jë¤Ç!ş™‰ßÏ¨…ø$ÚÎq¸€ˆJõ!­£¶ }à=Äç >ñˆC¿†c‹ëcˆÿÀû@´¼?¡5×v†2ŠÖ†53Ú®% âï`â—‡ñïæwAÄoì¡µÙ^ôñÏòß†øêŞ×@ü'úCœCğ~âAÔZÃáß†|ÿšÿÒóp²«Òä÷‹ä'ö¬ÖÂşXÔJO—­E«¼;˜§İ‘¥ø.Èògë<ëÛ-ğƒø€äí_˜òÿ½Q"ö0¯Ø=àĞ»ƒ@ˆvR7œçk×»£À= åÀoGAU ¨Ãw0_¨à\<™–srmÅ‡>:´¥àÍúÊÅÖæ}İ”·ä¼÷ZßGÊm,ğí(‘LÉo_@Ğn‘7ï«ªÜ#ğ•(p‘·Svµ}{y… ö(/o(€\Ï·€È·! ï2ßÆ G¾Í/„Æ”ò¬Ş'yVïƒ<«üÏZÔñSK¥"{GI-}ùñTi-•U*kúJ½7¡cş'Å=Ú„rÅsK?ÄŸtZ­ôÄQÛ«Ôö*µ½Êÿö*Áè/tI„>œˆg¦ÍfN?s8vÌ˜QcÔÏ))ÌØqñÈ‹GA±wfõŸ3¼´wÆ‘ç,J|¦w• œ˜ky"“W
Š	[7½¨bú&oîuä^ÿ®pî¾¹B9Q(&;¿™Nû}?%ÊÕŠÿŠAµ€P-LÓ‘w$•“wUÌ¡~Ó¥j6UNhò²À»&çUy!æ3•kÿ™\1İ*Öş³òÒ+¡lÂb•ã]l ¡%N SæÍÁ²ÑYÊs(jÌhAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAÿ?†÷Ï‡?jÎ¿#„¿í‡ŸÃû[O¿ğ…Ÿ§;,ágé3Sfv@ ©c ˆ¬V‡m¥ÃWMM¯*æÃ:%]ƒÿo[á_/;—Ø¯Hï´ø9¶YïÃJzF¢ê½ÿa|I^İæ°·§÷ØºN•ô¢Tb°Zsì²‚â¥Wèß&¢·AòÇrĞµ£ç,^QPœİÌ+é€Ş°qÔ?É‡uWwW7§“lÎ4[§Ï3/Óo<¯ê)êHW¬Ö¥%¿~vL¯\ç££WÔG›ãw}A±ÃVVŠŸÙèˆü=àt"‚Xÿ³ùTœ(W¥ª ä“Æ³¤¨¨¤ØŸÏöô¢ò}E]§¥vã¹Äno'7…>¹)Şqÿ¤ø´p:i©sğ×Ö3U5“üû™4ØwVI÷p!ŸU–˜o·•ÙG8ÑHl£F¤—•ÜfËqØG,ÍQ\°²Àvm™mymÅˆv?Oa4´Ní·E¸eøö¡Ú¿—±O1ÿğ"¾3KŸxä¿‘‡;Ğ¥(ï(Ô>$¾Á¥½¨üğ¹/\84nJı_şÚ#{Æ¾7ñ³Ó&/Ï=Áqõäy¡[?†¨†ıÆx¢%t$‘o„Ó^†BÀ8o•İa+>M)‰ÁD§(eâ»¸áÄ7†>„³61Ö$ı´ÿ¾Xòê–óK¥-­Vİ–³ô[NÏ5l¹tGÀ–KÓ¥šŒU»uIŒ¡üç[XuTMv'¶ñG=«‹eì”;è‰©P'.€ÿ\aÛUsœ?çAªc€ Ÿ3F×dÀ¹› |BTc‚òÌ¶õÔen€vbß`·¯f™›)ßòMúˆºz¸î,ÔkÒGÖ=ù/u¬y?Ãs‘uGáü1}T]”7±Ñÿ`l+~¶µ_ZÏš$VÑ	ÊO„°±v{¥ebß£ |"Ä›¡/wj" şÆ¼^50 V}÷e³t,óã@ÖuQëšÄnø®Ç~fAŸ«€^l;µû²úÉ*™™Ä>ètå.<ÇØíIİç­îçûé“ÚÀFí‹jšôİëtååzˆ¯ =	ÎeéÂkä²­P–„Ÿ‹3±‰•š´â n›pé—dŸé0NÓ`¼Ì[.–ìİÜ ·~\×İñAˆg¼õ$?İ–K¬æ´^ªC~³:‰ş£,oüßÛ ?0¡ŒKwLƒkÌ@{7§‡uB_lç?MÑOôT×»R[)Š¶¦ıD[P~Rä¹½	WiO–Í©¡nÛ½¯5²SÓ%–ÉÇs¯šLhå>ÒşD{ƒî‰Gì:c%øºj£Yª‰”’Ú¶Il+êRé.^ÓòOxõ¬;È$úQz&±ÑNhcÛ¢ğš»t‘Í^]ôqŒ–©ùàífƒ]@»ç¡ĞiÜúQ²ÈÖETâõ§®pmG|sİ¾
ßÇC:à;ÛŸïÃ!>¾?
é˜ïC!?oİÕø6¾_|æÇ÷?~&ßéáe}‹Cº“ÚŒ@wsEŸÖ3XMD¹?_MÀOèrrëÙ-·åŸ
>üP&,2oˆf·Ïòx¸¿É÷x:
´…íšül÷ ·¹â–Vğ»ÕñĞn<´;U26g„¼ o5êşŸ€öGKÆÊ'¢Øø£Ø?¨~£LŸÛÖ^~í<ıæòğ–m¦²$èòŞQ?š.x2…zK^‡ö%èÈìı–K»…ÜÎt(·Ş­J™Õ‹qí|uï
d‰|ñüùƒ…BGõú:¬+ë±õe¡Ë¦š·/ûpmæY“ëhšAoöÏÊçËÑ7@Ù=úˆ`1tøß©=Øíñ0V÷²N03vİ _+….»êÇív V’NİÈ2Oêƒë6°š-ºĞÊÚiÔzÆ:şÙw†Œ‡üÆ vhok`­ãtÖ5?I	<à8ì>eÜ|YŒ9òö"ğ½¹bq;Ù…~‰ñròE?¼‡q6ĞéÇe£çãõq°KÖ9ÏK²Í¹İ¬KÌáPæÑš©—Øí çÌN0À¼ÑÉ¶úk¥ÈÊçïd¿×wª{RJzş/Áw=ÿ·]Ã*›º>1ùh×?O>ÖõñÉ_u}lò}’tÃó’tğ=Œ—=Ûb¥NÍI­ÌØà;H‚¾w¾ıÎ†IÌ’:]r*†|¼Ô	bde|vĞ´ŞzñÙ]C*³jb/ÎêÇnx¯{1Æ%VêÜ|ô´'óoOô0¨¿	Ò«­PÏ~ÔÔÖêÎ€<Îêuu­ wçÚé]ÏÖ&(‡ù.Cñn°‰6\°ònGõ1usA^ı ü¢‘m<åÂvzpùŞÁu´G]gH_elŒ»{Òª‚ë2b¥àeÜ¦‰Æuy\£ù:á+‡ã`S_Ã˜,B[^Ôn<Ìzyœ¯<ïÊôıc¼oÑ@?
èGıˆºo .ÆÛ`0æ/Â9ğ×ld¸Vi‚”á<WÛ¯F'~ª„¯6A¹Y*Ï ?Ñ‘/TûÀ,ÛŠ6B¨ŞØûQ‡vŒŸŸÅ~w¯k•õ]a÷0¢L#ê`İµ?íŞ¯v
·Û'…EŞjìØÿ™½¶áïû°n0ø7?;ëCêúŸ…@ß³›ô_[èÀgIuØ_£©<Ãh¨-C>îÒoûÍ\	¼€¼"`MöØ\òwèÈ´^MÇó§®ç\¯Œ…>~ÌeU÷\Û •?€ü‚^ÒC”ufù^¬÷‰Qøc5Ïç—¾ú"ÖA9øŞ;À6ôRÚ&ÎAÛ­@Ï-H·wpš1Àk{}àm»GİvoÛÉĞÆthk´i}ë
k©ıÑœw9Ÿ‘u›ŒÂÏ?MãrË÷¶Y÷Äøóè¥ƒê¹ey†Ú0ázÖj÷Áõÿ`–q¸Ş†ù7±Æ
t!â¥I«ïü7Vèdd] ŒÇsåL¬ıçyFàO3DÈuf‘ŞÂı@[_ûw¯Ë2Š{¹İÛ½ıöùièsÍÏ•Ë­FÙN@&—°½îuc¨<ÓäòshÏTĞ¾,h(hOûÙ´õuhgIeŞGÀõ;ÚÉ6ªîo—„lwxe©’mTİ—d_)Ö|_A?>ò—mÏßÀ»QÁûa’ëú ïúßÈ{KPÇ¼—şŞ·vÀûïÿ
úõ¼¿äã=xŸ«à}Ïo ıwí1DûAíçíG´—í
ÚúmcVq…1ÓÿŒ1›ÙÁ˜õUYñÏî_ÇsÁÍ^ş#ë†òö„Ïù&P–ATİüßØÆ4Eo]ôµäkcòÚhµ¶_çÿsÌi÷šcÎ*äqĞù²¼£ëşzQÈûK¯¼£Tò®k¾(Ë;Šß¯ı<}Úè/ó®Aíıo«uÏïåd½3ÂõÊuŒRÛ}z¸æbûµKn omãPœ-Ğ§«ÍbíÒÑzäJ÷n¸æJ2>K:}N¥ÓïŠyefg	ãÒ/ŠõÉ££g#¨¿³.Šû+¹î1’gJo^Y§ç¾	}yNÏFã³,Zó=§Éh«Å+‹ˆºÍ^šf ¹ëéë½üEÔõ¸¨´ÁîuGvñ_¿ŞïÜ©è;ó¶Q÷Åx®ümv‡:Ã×İX„íŒ‚vyÇ#¢îQ/‹c[©>÷‚ÏÆÓmLü%6.tïÙ÷8hë\q2<PØxç+²îÒ¥İ
?™èm7ºnPàÏ·×Æª›Â6]sÄ[¾qêüew>À'»w²û[€Ov§~ÉZÕz®'YÆEÂ:Uyíà=F’Ä2­„Ük×êHpŸü¨s†î?¶øÛğ»¿dMê“ƒ|ı+
Ø·á‚ğ)D›uŞùÿ‚¿=NUõ£.à—Í#Wòq(}—Kı‰¼àïãº^èØÇõVõk]À•uğ—êq€Ï?:/Ûtƒºß+À§ûy¿D÷ÛË<Õ¸ô'9|pŞ\Ş?ï?.nƒ?ÿÉ¿ŞWğÙŸì¯Da×şÚ½´›ÏÚK´£~õú¯ùÖt¼ş«8ÿÓë¿}çÛ¯ÿ¦øôŠÓÿŞğóú§Z‡4ªÖ!²<>1øä±è|ûuÈ4ƒoŞÊPœÿ—Á'³·ŞuHãÏ]‡6t¼ıö·ÿş÷nÛh”mã¯\Â†tĞÿnß³€şç…íŠçnbîxÎà³‡8‹Ûñ!IJ>ÚÛ\ÅçÓJSóÊÑ(Ï	NƒÏîZÛÚóÑ¤÷S‹â<ÚŞZƒoŞÈû…<ÈÏ{wq:~Î#øğ­ÁÏÒ³O~zµÃeSgæræ>sOü<§÷ù´×Û”ãÍ×âèS-^¾bê8_7·ã«Ÿ_şÏ.–ˆgG•ĞVëÊFy]¥Ğño /¾ue7ÃÏYWzıŒ×®$…]­k~æ½Ïf.êÕÂ«/'ò+ló÷Åûô>}8v…v®&CzŸ<æí“zŸ<ŞÓ·—ÇÕhíPĞú/ 5]Aë5ı¯“mÂV“lßWÈöiıoZwz}Kµ·¨ºî¼Ÿ_¶ê}~Ã¥ÿus®Ÿıëößê[şN1–%úÿ¶ç³òóÙŞvcêğvÛ?§-óö¡Gİı¯~Në¿‰Šñ{£UŒ_¼büÆèİ³Ù/)ıP¬·­èº§x[ş÷úãõ>­ÿ¥k¶«·ÍmWtĞö+:_Û­º+·ı[Æ÷Kïùû’VÙOÄ´ã?é|cü‘î—±¼w­Ôç:1/ïÒùö}+tò»Qœ÷?0¶Çû+oÛİë.œóí[¢­Óá’XûüM÷Ë}Ù:Ÿÿ)şïÓùüÏ£ºŸöe™HK‡ûV¬¾ßş^œf¸¯Ú­[ŸqYòÑ^Øê»§×±õü|‹DûN,®FÙî{]u¿îñ:^»õl•÷—?*f£ùšü8+©ÕO~~GEtë“zİA¡<c)ğ¶Y¿pû‰›ÈØòù2ÜGÜÄ27ëoÚ¾!ˆ1zˆ¬¾¬-Z9ÚYmBßîÒ³šs¬+ÖõèŒËt,óÉºƒ8V:©<#iW,Ø+Å,3ôH[mèzÓêz–y®Û¼{Áv]?vğèc8Ğ×%µ1İÔa¾ª1öxûšÆJÆ —5bşŠª›ôöë’^Ù¯3VFÁµIú¤6,g µ<£Åú.¢.°éBĞ8ÄY@óc'Û“à¤…ãrd®ìûôó¾Ö~Yû–­vL—^moô	×FWÛî
ãÅjÎƒ=fuÓoYÒ…mñ7}ÏÖ,T“İµÉëŸB )ëVù"Ô¯õ« ®«7ìUÃ¤†)åºò)Æ£I­1±fŸ&ÕÔ‚<M /7´—ÅÚ‚“YRÎX\Îjâ¿[ó@´|Àô¹].‘j>„:¨Ÿáp}pR×­×ÅÀuà7y[PWJóá’XK3,K>.Mîóµ½yŸyşöŞ5MĞ÷`à=XÏÚŒ·'µí¬u+µv¡š+ºàW4Û¯¡LîŸÏı•!x>†ŸÿÊbXùn}ÏºàõI­1A¬æmg›±;ë|çÄMİºsÍjº¶d0ŞÀ¶‚Îêö}üøP/|O®~ãğŞ5½¡¬Ä ĞıĞË+Z7¯×
zT«n®Õ±L3”ñççg=5]öŒ8¢nà,ÆF_„ë~ }Är†?SZÚ»&Îá»JmİşÔ³ÎaØö!õ£ŸT#Œd=@z»tÂwÀ½“×wduKj;}ÙóĞ]A,ÑıpÏ`ı£=·‰o}ppä†Fé±·7oyöH\ëT(‹‹tõŒ—şÔ³êìX×*ûO+È0«gR[ìdöbÜ›eƒN.é’´%·oRÛ×`#×Küg #¸®BÎUg ùQp¶­ÿuöó,û	ûÙÀíç´>æ¯ ˜Ë0—éëÚÀ‡\Pû@´¥»}÷ íT°û¸eãc×²Û×_ñøŞ‰~
ßõ0Â˜÷›_9$?¼5İïxY×Š÷tŒP/êõƒzÁRp§©—ÂnwCù eí€V$¾Ç´–gH[î¸•mI]æ?hâ>ğ6Ğ•:QïéçKø.häÔ vpH“Ó{RÔ;uŸ Åß }8|ÇšVc[~BŸ|j-œß_ã
c]ãA·‡€n§	İ®Wêö)ôÀTH/èCVÜmªÉ‚xLß‹¿Ç´äâ¹mÒø×~—ô‡åw‡Ã¹ğš£`;òù8ÿ%œö¹Mb£Ç‚ßİıˆ‡¹/ÖqëY«lm?ØY>È<®ÔÑ•gt‚~{ë¸B]¤sEüÜÉ•SâZ³±!I[r¢Ì[Ãc ør˜›eªÿ¥:6¼ñÒ;`Äçæê~ÉÑ59@3¢_yBLÍ-P¶H]néQ³ Ê2!r¹¢\c?æùE¾›"¥È÷Täû*òıùÁŠüE~¸"?R‘«ÈOTä¯Sä§)ò3ùYŠüE>C‘¿Q‘_¤ÈßªÈ/QäóùÛùbE¾L‘_®È¯Vä§Èß­Èß£Èß«Èß¯È? ÈÿQ‘D‘ÿ³"ÿ”"ÿŒ"_§È¿ Èÿ]‘I‘U‘S‘ß¥ÈïUäßQäßSä)ò+òGù/ùcŠü7Šü¿ùïùù³ŠüyEş²"¯3ûòŠ|ˆ"ßE‘ï¦ÈG)ò=ù¾Š|E~°"?D‘®ÈTäÇ*òùëDÿ*=Œ±füƒkrÊ´ù3½(İœ™™’1Ç‹3Í3S2ÙÙeÙK
mv“ª¢)»8×ä_ÙTä´;LKl&»Í1<ä×]š½Ä^RètØLøcv•vDŠ²W™ŠKÄE&»s	4j*ÉSÑ7ÓÜbZ`Î˜“:gæDSf~İ´ÄYP˜kZ‘m7áÏP,u–Ù 8òKœÿeSşxèRv£İ¢ŒÎF°ıØD–|SZ²5uÎ¼”ŒLkZê´sFjÊ¼)jÁNQIv
ÿ{Şƒèo?¥:ñw"(7@™!ÿbNu‡Çq1Qş»´Åü½Q(Ì6‰¿&1¼„6ëXÀV€‡Xàx#3ÀıO@=LC˜îdÉT&§†®L*íÆØÀî°"íÎt¡°ĞÛÉ$LÆ&õîÁØs½˜´²7œÜ‡ÅôeºÜ¾ŒÅÅ2]t´·‰IÕ°h:mbúò~Œ}ÖIögúÜP6€é6d†“C™1ZğdĞşjRZĞ‚´ …ÿBx¹D©R=¥J(¤4ˆR#¥Á”†PÚ‰ÒPJ;SÚ…Ò0JÃ)íJi7J»SAi$¥Q”FSCiJ{RÚ‹ÒŞ”ö¡´/¥±”š(íGiJP:ÒA”¦ôJã(§t¥C)Féµ”§t¥	”&R:’ÒQ”¦t¥c)GéxJ'P:‘ÒI”N¦t
¥×Q:•Ò$JÍ”N£t:¥É”¦P:ƒÒ™”Z(M¥t¥×SšFélJçP:—ÒçÂÅ¹ËãÑU`Y–õá4aYõİ–Ç!´»À2?ù„åq7F,ëi.aY‘ËúšEXÇ×	Ëz%°¬Û	Ëúİ;Z`YŸÊ	Ëzš#°¬gÇ	Ëú&;œÉr|—°,ÏÑ=–Ça#ay<ø¼–õ%—°¬7M„e;™Ü[`Ù^j	Ëú›ÜG`Ùn÷–í7·¯À²ı}FX¶ß¬Xe=y°¬1&e=ÙNXÖëÂ~Ëú=¾¿À²~_$,ëıáËú8p À²––íÕMX¶“Ñƒ–ıX9aÙN>#,û…ôÁËö¸•°lgI×,Ûıc„e{Œ‰XöO	Ë~j`¼À²¿ÚJxÄU¿f¡-hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ …ÿ›‚‰‰ßÒ®–DªüÙiùc?1ªk8N
ôı®8]'é „åR.Ä{!n†¸âq</1i8ÄLˆ¹Ë –C| b-Ä îøÄ“/Bì¢cÒˆ!Î€¸b)Äuk!¾ ±â!ˆ'!†è™Ôâˆ!Î€x#ÄBˆ«!n€ø0Äg n‡¸â‡C<1Ä <@Ì€¸âSßƒxâ÷˜d‚˜ 1bÄ•ïXq+Äˆ› ş ÑÈ¤ˆƒ!‡8âˆË!ŞñˆõøîÖœüevÇ2knvÙŠ‚b^°2Ûší°­,p ²;²s–a%k^vA¡ÉRgvY®(*+ÌÉv`¡–®RÀbÿ³Å¾³¹«
s­KmkAQöR›µ8»È&—Š’œg1ô$;'Çf·3ë’Õ¶²ç”a’W˜½Ô™¢’\LJV 9…%Å¶¼‚B›"›íàÀe¹…%¥6¨–[ZVPìÈcVÛÊœüìâ¥¶ÜlG6"[Îr¦(‚<Ñ2^Ç[¡4$rÊòá¼2e@X<f;@,v@çrVäòÔV¼œY‰‹Â‚âeâˆµ°öJ¼²v›ÏˆË‹lE NH—q‘ğ„—/Ë+ÈQ‰àK1åõğjøi3È•ØVZí¥ÙØh©#¿Ì–k-r‚
Xsm0Z%«ÔÅÅ(ÿ²Â’œeê2g±(Å"q<É9ìP™­¨d¹8+³	©8-r+­Å¥2¢|çÃ®”, ¢$dƒÇ<;¦e¹ÎR&+*“UTdP>\+‹°Êª"ÑIÊ`mG™5:æ,ÎµÚDNT)Ör:
ŠlÅvoÖÈÊŞ5rÇV^®ƒãüä‰.;×–Ë‚A0az¶!éÙÖYpX7¯…Ãöká
dn°Ğî¡¨Û	¨côlÿ$¨±g¢Íd0]>›èÕõzæî' ÁÛÊX‰}6Jë­*T|­Ä5üIÏcûƒ~%D'ôûIh÷³Xa2Ãfê%…ï‚ò¦qØİñppf,Àk%OJ9lŸÄ•îˆDvğ¥Dvp.Üx¶˜üA§g›2P"ò>¬CSx
ÊÕ'Â¡>ëî€²Ï®‡º ô=:ÙŞƒÒúAŒé…Í¼ª+`èøØ‡3å©pù&^~`Ó¸åZ¡ç¦Q¥×ã'ç@şóàP;A‡İ×c…gàLÃüÄ|Ş;a)¯é–Ò UE¹Eú_ lLx1'§I\I€ÒíÉ8¤f$~NÏK+LO¦ğ•Ş§ıßé¹òo0€HS¡Yû“ëøËPòØ\ìçl¥¬Ş6àtùõpú¾Á(»àÆ1X{4vì4fs°(”ï¤İ¡RÓuPéğL8¼;
ù…ÕŸ	 	2€W}6 †+	{*JÇx_€½‹Ù¶ Ôtv0€u!İ/‡e‘ƒÀ*¥<vB×Æşª+d'tEËØz~öY}){K_Æ^7ØÙ=^{,ÀÉ¾ Ú…%,²h••5Cóå™Ü‚ôĞ‰Ö0È®3!eÂ¡5şCéj@-äÉ7JßÖÂ=±fçæ‚gCGh+Î) ;ı,j	4°ıÜJ9ùÃ·¢.Ëì6«=ß¶ì‡½äÈÉ·‚Ÿ.eA|0le † Ş8UöV\ºÁ‹*Í¿å`àÌÉnpæt¸l9«62½¤p¹Mö5VVn\QVà°qïÌ4Â˜"¿‡Ñmt²²Wy×
áò¶7syÎÂBv ˜±ãç)ÙÁÀ;ÿ>%û8°ˆUYpb*eMAe0¬F°2‡¨½Óy½è¦:½«/,m•Z¥­º&Ã~Ñc<.-Ì_'-~]Z¼¸VÂÿ˜ææÖK[¥Ç¤´ü¬ÂÜ5‹s7Ië ­\Ç+m•Ş…UÕgRÚâü´´ÅÜû¤ÅkÖTKÕP»^ßø¡!†x™AŒu…\ƒøàË%œ/>ôÄ„“Än˜‹°…ğŸ	§şáçè»—ïŞCø(áÏ·"†H"b’QàjÂa„k	Ç®'ÜpáxÂ„7H¸…ğtÂL| ‰Í%Nø&Â&ÂK'¾pa'átÂwÎ"|áRÂ5„éLìa™ÂOÊü®“ù'¼MæŸğ™Âdş	,óOø+™ñá'Ö,óOøŒÌ?á‹2ÿ„ÁÄ?á(Âé„Î"<šp)á©„éÃSÌB¸šp&áZÂ·®'œO¸°“p#áu„›ÿáÂf)$oÂá„·6~‘páWeş	ï•ù'ü¡Ì?á/eş	ÿ[æŸp«Ì?áÀâŸpázÂ±„Ç#QnGÊø¤À:²)ùËA	ãçµÂÀ>Åw³ÿbñ]$ OX|7‹±±„_'l&,¾‹Åøw¬‹ïH1v3áı„	‹ï~1¶’p>ù“{	‹ïJ1öañ1Æ6Î¥ş¾L8†Ú‹0}@} ×'z_ßÅÂ÷X|‹±KrÄÉXˆDôÅÈX/Â	',¾Ûş†pojáò¿é„^Lø3’÷2Ââ»gŒ-—é‹ˆÁ:’ø#|?á,G×?›Ÿ&y×ŞJı}ƒ°ønøÂTÿ3ÂôÁ/öoÂ¹„ÏßÅıÒ‘>˜&,¾ëş°øcã'<“°›øË üõ/‡ğVjïvÂ¡4^w¦ú±ßßQƒq#¼‘ğ_‹ï–½ßÿ*ÓëAò!ü.áO	Ç¿nÂ¯½Ó„éƒdVãÂH^zq¾U|p‘EÒy‰ì³/Ï§ëÇ.%{1Î$û˜%Ó¸c‹ˆ…èåN'\HõÒÆî&#>ˆÇ$üp'ò„sÅöØNÂZ?¼O¸0˜æÂ÷ßQû©ı3zş\ÉûH
V„~8B…«ğ¶¨ğÎSa§
WªğŸUø~^…·ªğ*¼G…¨ğÇ*ü•
ÿ[…Pá*à»ªp´
÷Wáa*<V…“UøzÎTá[Tø6^¥ÂkUØ¥Â5*ü
?¡Âu*ü¢
oWáŞ§Â*|X…¿PáoTø?*Ü¦Âş¸
'ªpŠ
ß¬ÂÙ*¼L…W¨ğ:¾O…ÿ¨Â›T¸^…_Vá=*ü
¨ÂŸ©ğqşN…Ïªğe
òÇá*ÜK…©ğ§ÂfNSa\ïTB¬Â¹×«øœõâÿ€súa”5ê7Ş3@üÎõ¥5Òãè«Pß!ÖâºâS8¿á˜@|}Ä¿ÒjÚÄg!>‡~âÿ†c†vñïx‡>ï; ¾Dë­í_Áµ0Ä× ¾~â›8_ÒÔ¶â.ˆ»qŒi]¶íâ~ˆoã½"ú?ˆïBü'=ÎhSB<Dë·!~„¾â'hcè²»O“ß/–Ÿ‰Y­…%ü±¨•$[‹VyŸùcø‹,=ô€?øYşØœg} ~ŸÍb¼àËÓS^â¿ JÄ– æz7ÑÆ€@ê†ó|íz7	87
øm¨
uø¦æœ‹‡ÒrN®­Ø<àĞG‡v¼Y_¹Ø=À¼¯›ò.‚œ÷^ëÛMàH¹£€¾GÿJ$SòÛ´äÍûª*·|%
\äí”]-Gßö G^!ÈÛ</?ÿW ¹o ‘o/@ ße¾=|û^)åY½Oò¬ŞyVù9µ¨ã§–JEö’Zúòã?!ş¨ÒZ*?ªT>Öô•zoBÇüNŠíÿ2z´	åŠç–~ˆ?é´*9Zé‰£¶÷¨í=j{ÿc{ íô“T$2Îƒf;?3-uNJ²uÆü9Ó3SçÎ±&tT˜ˆWÎL›;ÍœÆ	YÇ3jŒšüğœ’ÂÜá‰ì¸x{'Vÿ)Ã;?{'yÊ¢Ä7_z	ÊyY±Dç1y¡ ˜¯åiÓ;*foræ^?îuï
ßî›*”ó„b®ó›èä©ß7ïS¢\¬ø/TëÕºD1yÇ\9×xgQÅê7[ª&Så|&¯
¼KyZ•×aŞ)S¹´ğŸÈ³­byà?)/½Ê&,9^ÏÒ\âD:³m0‹äÎ,,Y’]h§û—ó_„ÂrUú\ñZQ”á[Bo3@ã#èˆ™÷ô¦,“>¹ÿ“aØh9×î'ß6±·÷İSõ»©|ÿà¶ÒÓ‘{ï?æ­ĞZwúíŸı¹®*öHÆ¶ÇîòÙKB6Ì»ëĞ˜€õÃGtJ¿±±şëÒïG:x‚‡2~YtgèâÒóc"QúYÕ„ò;gâwˆßğQnuúì×+>Ø¼ııÇš¶}tèŞásœï›Ğı©A7¶f½˜³¨á5M#şõÃ·é6OŠ¿ÕgñüõÉî9Cüó÷‡CïJ¿æxïÏßõÜß–ì=‘×`øäàÁeº¹<k¶®Y½şÈ•×°¿şÖóöå}şbRY[œcZæØvìÒ”–ış8pìÜ¦ÒŞ‹sSÏ7<úÈÄëf¼<Î³eÑéÕwÿ§è÷¬ûÛ}'ÿqÏ¤å'ì\=åô¡–É1×7öşôïe,Kû®äCÏbS}æï,=İüôuj¯ÎiAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ -hAZĞ‚´ğDø_Øê?^  [?1049l [2K[37;2m# (tarball data)[0m