#!/usr/bin/env bash
# Nix wrapper script, generated by Nixie (https://github.com/nixie-dev/nixie)
# Nixie (c) Karim Vergnes <me@thesola.io>
# Built using Amber 0.5.1-alpha-nix-dd1b7dc (https://amber-lang.com)

[ "$EUID" -ne 0 ] && { { command -v sudo >/dev/null 2>&1 && __sudo=sudo; } || { command -v doas >/dev/null 2>&1 && __sudo=doas; }; }
split__5_v0() {
    local text_257="${1}"
    local delimiter_258="${2}"
    local result_259=()
    IFS="${delimiter_258}" read -rd '' -a result_259 < <(printf %s "$text_257")
    __status=$?
    ret_split5_v0=("${result_259[@]}")
    return 0
}

join__8_v0() {
    local list_265=("${!1}")
    local delimiter_266="${2}"
    local command_1
    command_1="$(IFS="${delimiter_266}" ; printf "%s
" "${list_265[*]}")"
    __status=$?
    ret_join8_v0="${command_1}"
    return 0
}

parse_int__14_v0() {
    local text_2789="${1}"
    [ -n "${text_2789}" ] && [ "${text_2789}" -eq "${text_2789}" ] 2>/dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_parse_int14_v0=''
        return "${__status}"
    fi
    ret_parse_int14_v0="${text_2789}"
    return 0
}

text_contains__17_v0() {
    local source_22="${1}"
    local search_23="${2}"
    [[ "${source_22}" == *"${search_23}"* ]]
    __status=$?
    ret_text_contains17_v0="$(( __status == 0 ))"
    return 0
}

starts_with__23_v0() {
    local text_26="${1}"
    local prefix_27="${2}"
    [[ "${text_26}" == "${prefix_27}"* ]]
    __status=$?
    ret_starts_with23_v0="$(( __status == 0 ))"
    return 0
}

ends_with__24_v0() {
    local text_2876="${1}"
    local suffix_2877="${2}"
    [[ "${text_2876}" == *"${suffix_2877}" ]]
    __status=$?
    ret_ends_with24_v0="$(( __status == 0 ))"
    return 0
}

slice__25_v0() {
    local text_241="${1}"
    local index_242="${2}"
    local length_243="${3}"
    local result_244=""
    if [ "$(( length_243 == 0 ))" != 0 ]; then
        local __length_2="${text_241}"
        length_243="$(( ${#__length_2} - index_242 ))"
    fi
    if [ "$(( length_243 <= 0 ))" != 0 ]; then
        ret_slice25_v0="${result_244}"
        return 0
    fi
    result_244="${text_241: ${index_242}: ${length_243}}"
    __status=$?
    ret_slice25_v0="${result_244}"
    return 0
}

dir_exists__41_v0() {
    local path_248="${1}"
    [ -d "${path_248}" ]
    __status=$?
    ret_dir_exists41_v0="$(( __status == 0 ))"
    return 0
}

file_exists__42_v0() {
    local path_282="${1}"
    [ -f "${path_282}" ]
    __status=$?
    ret_file_exists42_v0="$(( __status == 0 ))"
    return 0
}

file_write__44_v0() {
    local path_2864="${1}"
    local content_2865="${2}"
    local command_3
    command_3="$(printf '%s
' "${content_2865}" > "${path_2864}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_file_write44_v0=''
        return "${__status}"
    fi
    ret_file_write44_v0="${command_3}"
    return 0
}

dir_create__47_v0() {
    local path_247="${1}"
    dir_exists__41_v0 "${path_247}"
    local ret_dir_exists41_v0__87_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__87_12 ))" != 0 ]; then
        mkdir -p "${path_247}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_dir_create47_v0=''
            return "${__status}"
        fi
    fi
}

array_last__74_v0() {
    local array_2782=("${!1}")
    local __length_4=("${array_2782[@]}")
    local index_2783="$(( ${#__length_4[@]} - 1 ))"
    if [ "$(( index_2783 < 0 ))" != 0 ]; then
        ret_array_last74_v0=''
        return 1
    fi
    ret_array_last74_v0="${array_2782[${index_2783}]}"
    return 0
}

array_pop__77_v0() {
    local array_261=("${1}")
    eval "local array_261_deref_86=(\"\${${array_261[0]}[@]}\")"
    local __length_5=("${array_261_deref_86[@]}")
    local length_262="${#__length_5[@]}"
    local index_263="$(( length_262 - 1 ))"
    if [ "$(( index_263 < 0 ))" != 0 ]; then
        ret_array_pop77_v0=''
        return 1
    fi
    eval "local array_261_deref_87=\"\${${array_261[0]}[${index_263}]}\""
    local element_264="${array_261_deref_87}"
    local slice_upper_6="${index_263}"
    local slice_offset_7=0
    local slice_offset_7=$((${slice_offset_7} > 0 ? ${slice_offset_7} : 0))
    local slice_length_8="$(( slice_upper_6 - slice_offset_7 ))"
    local slice_length_8=$((${slice_length_8} > 0 ? ${slice_length_8} : 0))
    eval "local array_261_deref_88=(\"\${${array_261[0]}[@]:\${slice_offset_7}:\${slice_length_8}}\")"
    eval "${array_261}=(\"\${array_261_deref_88[@]}\")"
    ret_array_pop77_v0="${element_264}"
    return 0
}

array_shift__78_v0() {
    local array_277=("${1}")
    eval "local array_277_deref_89=(\"\${${array_277[0]}[@]}\")"
    local __length_9=("${array_277_deref_89[@]}")
    local length_278="${#__length_9[@]}"
    if [ "$(( length_278 == 0 ))" != 0 ]; then
        ret_array_shift78_v0=''
        return 1
    fi
    eval "local array_277_deref_90=\"\${${array_277[0]}[0]}\""
    local element_279="${array_277_deref_90}"
    local slice_upper_10="${length_278}"
    local slice_offset_11=1
    local slice_offset_11=$((${slice_offset_11} > 0 ? ${slice_offset_11} : 0))
    local slice_length_12="$(( slice_upper_10 - slice_offset_11 ))"
    local slice_length_12=$((${slice_length_12} > 0 ? ${slice_length_12} : 0))
    eval "local array_277_deref_91=(\"\${${array_277[0]}[@]:\${slice_offset_11}:\${slice_length_12}}\")"
    eval "${array_277}=(\"\${array_277_deref_91[@]}\")"
    ret_array_shift78_v0="${element_279}"
    return 0
}

env_var_test__119_v0() {
    local name_2780="${1}"
    [[ ! -z ${!name_2780+z} ]]
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_test119_v0=0
        return 0
    fi
    ret_env_var_test119_v0=1
    return 0
}

env_var_set__121_v0() {
    local name_270="${1}"
    local val_271="${2}"
    export $name_270="$val_271" 2> /dev/null
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_set121_v0=''
        return "${__status}"
    fi
}

env_var_get__122_v0() {
    local name_16="${1}"
    local command_13
    command_13="$(printf "%s
" "${!name_16}")"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_env_var_get122_v0=''
        return "${__status}"
    fi
    ret_env_var_get122_v0="${command_13}"
    return 0
}

is_command__124_v0() {
    local command_66="${1}"
    [ -x "$(command -v "${command_66}")" ]
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_is_command124_v0=0
        return 0
    fi
    ret_is_command124_v0=1
    return 0
}

printf__130_v0() {
    local format_38="${1}"
    local args_39=("${!2}")
    args_39=("${format_38}" "${args_39[@]}")
    __status=$?
    printf "${args_39[@]}"
    __status=$?
}

echo_warning__139_v0() {
    local message_268="${1}"
    local array_14=("${message_268}")
    printf__130_v0 "\\x1b[1;3;97;43m%s\\x1b[0m
" array_14[@]
}

echo_error__140_v0() {
    local message_36="${1}"
    local exit_code_37="${2}"
    local array_15=("${message_36}")
    printf__130_v0 "\\x1b[1;3;97;41m%s\\x1b[0m
" array_15[@]
    if [ "$(( exit_code_37 > 0 ))" != 0 ]; then
        exit "${exit_code_37}"
    fi
}

command_16="$(tput tsl)"
__status=$?
tsl_11="${command_16}"
command_17="$(tput fsl)"
__status=$?
fsl_12="${command_17}"
command_18="$(tput smcup)"
__status=$?
smcup_13="${command_18}"
command_19="$(tput rmcup)"
__status=$?
rmcup_14="${command_19}"
env_var_get__122_v0 "TERM"
__status=$?
__TERM_17="${ret_env_var_get122_v0}"
can_set_title__173_v0() {
    local has_statusline_118=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_17}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_20
                command_20="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_11="${command_20}"
                local command_21
                command_21="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_12="${command_21}"
            else
                has_statusline_118=0
            fi
        else
            has_statusline_118=0
        fi
    fi
    ret_can_set_title173_v0="${has_statusline_118}"
    return 0
}

set_title__174_v0() {
    local title_117="${1}"
    can_set_title__173_v0 
    local ret_can_set_title173_v0__43_8="${ret_can_set_title173_v0}"
    if [ "${ret_can_set_title173_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_11}""${title_117}""${fsl_12}"
        __status=$?
    fi
}

enter_alt_buffer__175_v0() {
    >&2 echo ${smcup_13}
    __status=$?
}

exit_alt_buffer__176_v0() {
    >&2 echo ${rmcup_14}
    __status=$?
}

teardown__177_v0() {
    local failure_352="${1}"
    if [ "${failure_352}" != 0 ]; then
        echo "Press any key to continue..."
        read -n 1
        __status=$?
    fi
    set_title__174_v0 ""
    exit_alt_buffer__176_v0 
}

__SELF_18=""
env_var_get__122_v0 "0"
__status=$?
me_19="${ret_env_var_get122_v0}"
text_contains__17_v0 "${me_19}" "/"
ret_text_contains17_v0__15_4="${ret_text_contains17_v0}"
if [ "${ret_text_contains17_v0__15_4}" != 0 ]; then
    starts_with__23_v0 "${me_19}" "/"
    ret_starts_with23_v0__16_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__16_8}" != 0 ]; then
        __SELF_18="${me_19}"
    else
        env_var_get__122_v0 "PWD"
        __status=$?
        __PWD_28="${ret_env_var_get122_v0}"
        command_22="$(readlink ${me_19})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_18="${__PWD_28}/${me_19}"
        fi
        rl_29="${command_22}"
        starts_with__23_v0 "${rl_29}" "/"
        ret_starts_with23_v0__27_17="${ret_starts_with23_v0}"
        if [ "$([ "_${rl_29}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_18="${__SELF_18}"
        elif [ "$(( ! ret_starts_with23_v0__27_17 ))" != 0 ]; then
            __SELF_18="${__PWD_28}/${rl_29}"
        else
            __SELF_18="${rl_29}"
        fi
    fi
else
    echo_error__140_v0 "This script must be run from an absolute or relative path." 1
fi
exists_newer__180_v0() {
    local left_2786="${1}"
    local right_2787="${2}"
    local stat_cmd_2788="stat -c %W"
    local command_23
    command_23="$(uname -s)"
    __status=$?
    if [ "$([ "_${command_23}" != "_Darwin" ]; echo $?)" != 0 ]; then
        stat_cmd_2788="stat -f %B"
    fi
    local command_24
    command_24="$(${stat_cmd_2788} ${left_2786})"
    __status=$?
    parse_int__14_v0 "${command_24}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer180_v0=0
        return 0
    fi
    local left_time_2790="${ret_parse_int14_v0}"
    local command_25
    command_25="$(${stat_cmd_2788} ${right_2787})"
    __status=$?
    parse_int__14_v0 "${command_25}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_exists_newer180_v0=0
        return 0
    fi
    local right_time_2791="${ret_parse_int14_v0}"
    ret_exists_newer180_v0="$(( left_time_2790 >= right_time_2791 ))"
    return 0
}

bail__181_v0() {
    local message_115="${1}"
    local archive_116="${2}"
    exit_alt_buffer__176_v0 
    set_title__174_v0 ""
    echo_error__140_v0 "${message_115}" 0
    if [ "${archive_116}" != 0 ]; then
        echo_error__140_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

get_self__182_v0() {
    ret_get_self182_v0="${__SELF_18}"
    return 0
}

dump_archive__183_v0() {
    local command_26
    command_26="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_114="${command_26}"
    cat ${__SELF_18} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_114}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__181_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive183_v0="${dest_114}"
    return 0
}

untar__184_v0() {
    local member_112="${1}"
    local dump_113="${2}"
    dump_archive__183_v0 
    local archive_119="${ret_dump_archive183_v0}"
    local tar_cmd_120="tar -x -f ${archive_119} ${member_112}"
    if [ "${dump_113}" != 0 ]; then
        tar_cmd_120="tar -x -O -f ${archive_119} ${member_112}"
    fi
    local command_27
    command_27="$(${tar_cmd_120})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_121="${__status}"
        rm ${archive_119}
        __status=$?
        ret_untar184_v0=''
        return "${tar_status_121}"
    fi
    local tar_out_122="${command_27}"
    rm ${archive_119}
    __status=$?
    if [ "${dump_113}" != 0 ]; then
        ret_untar184_v0="${tar_out_122}"
        return 0
    else
        ret_untar184_v0="${member_112}"
        return 0
    fi
}

check_deps__185_v0() {
    local deps_63=("${!1}")
    local missing_64=()
    for dep_65 in "${deps_63[@]}"; do
        is_command__124_v0 "${dep_65}"
        local ret_is_command124_v0__145_16="${ret_is_command124_v0}"
        if [ "$(( ! ret_is_command124_v0__145_16 ))" != 0 ]; then
            missing_64+=("${dep_65}")
        fi
    done
    local __length_30=("${missing_64[@]}")
    if [ "$(( ${#__length_30[@]} > 0 ))" != 0 ]; then
        echo_error__140_v0 "The following commands are missing:" 0
        for cmd_67 in "${missing_64[@]}"; do
            echo_error__140_v0 "- ${cmd_67}" 0
        done
        echo_error__140_v0 "Use your distribution's package manager to install them, then try again." 0
        ret_check_deps185_v0=''
        return 1
    fi
}

get_osname__195_v0() {
    local command_31
    command_31="$(uname -s)"
    __status=$?
    ret_get_osname195_v0="${command_31}"
    return 0
}

get_machine__196_v0() {
    local command_32
    command_32="$(uname -m)"
    __status=$?
    local machine_2797="${command_32}"
    get_osname__195_v0 
    local ret_get_osname195_v0__23_8="${ret_get_osname195_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__23_8}" == "_Darwin" ]; echo $?) && $([ "_${machine_2797}" != "_arm64" ]; echo $?) ))" != 0 ]; then
        ret_get_machine196_v0="aarch64"
        return 0
    fi
    ret_get_machine196_v0="${machine_2797}"
    return 0
}

get_system__197_v0() {
    get_osname__195_v0 
    local osname_2796="${ret_get_osname195_v0}"
    get_machine__196_v0 
    local machine_2798="${ret_get_machine196_v0}"
    ret_get_system197_v0="${osname_2796}.${machine_2798}"
    return 0
}

get_nix_root__199_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_249="${ret_env_var_get122_v0}"
    get_osname__195_v0 
    local osname_250="${ret_get_osname195_v0}"
    local result_251=""
    if [ "$([ "_${osname_250}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_251="${userhome_249}/Library/Nix"
    else
        result_251="${userhome_249}/.local/share/nix/root"
    fi
    mkdir -p ${result_251}
    __status=$?
    ret_get_nix_root199_v0="${result_251}"
    return 0
}

get_cache_root__200_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_253="${ret_env_var_get122_v0}"
    get_osname__195_v0 
    local osname_254="${ret_get_osname195_v0}"
    local result_255=""
    if [ "$([ "_${osname_254}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_255="${userhome_253}/Library/Caches"
    else
        result_255="${userhome_253}/.cache"
    fi
    mkdir -p ${result_255}
    __status=$?
    ret_get_cache_root200_v0="${result_255}"
    return 0
}

get_repo_root__201_v0() {
    get_self__182_v0 
    local ret_get_self182_v0__85_24="${ret_get_self182_v0}"
    split__5_v0 "${ret_get_self182_v0__85_24}" "/"
    local self_a_260=("${ret_split5_v0[@]}")
    array_pop__77_v0 "self_a_260"
    __status=$?
    join__8_v0 self_a_260[@] "/"
    local ret_join8_v0__88_26="${ret_join8_v0}"
    local self_dir_267="/""${ret_join8_v0__88_26}"
    local command_33
    command_33="$(git -C ${self_dir_267} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__139_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root201_v0="${self_dir_267}"
        return 0
    fi
    ret_get_repo_root201_v0="${command_33}"
    return 0
}

cmd_help__214_v0() {
    env_var_get__122_v0 "NIXIE_VERSION"
    __status=$?
    local __NIXIE_VERSION_246="${ret_env_var_get122_v0}"
    echo "Nix wrapper script, generated by Nixie ${__NIXIE_VERSION_246}"
    printf '%s\n' ""
    echo "Available --nixie- options:"
    echo "  --nixie-help            Show this help message and exit."
    echo "  --nixie-print-config    Print this script's configuration."
    echo "  --nixie-extract         Unpack the resources archive into nixie/"
    echo "  --nixie-cleanup         Delete local Nix build files"
    echo "  --nixie-ignore-system   Behave as if Nix was not installed."
    exit 0
}

cmd_print_config__215_v0() {
    untar__184_v0 "features" 1
    __status=$?
    local ret_untar184_v0__32_16="${ret_untar184_v0}"
    printf '%s\n' "${ret_untar184_v0__32_16}"
    exit 0
}

cmd_extract__216_v0() {
    dir_create__47_v0 "nixie"
    __status=$?
    cd "nixie" || exit
    untar__184_v0 "" 0
    __status=$?
    exit 0
}

cmd_cleanup__217_v0() {
    get_nix_root__199_v0 
    local nix_root_252="${ret_get_nix_root199_v0}"
    get_cache_root__200_v0 
    local cache_root_256="${ret_get_cache_root200_v0}"
    get_repo_root__201_v0 
    local repo_root_269="${ret_get_repo_root201_v0}"
    echo "Removing local Nix channels and build files..."
    chmod -R +wx ${repo_root_269}/.nixie 2>/dev/null
    __status=$?
    rm -rf ${repo_root_269}/.nixie
    __status=$?
    echo "Removing user Nix store..."
    chmod -R +wx ${nix_root_252} 2>/dev/null
    __status=$?
    rm -rf ${nix_root_252}
    __status=$?
    echo "Removing retrieved Nix binaries..."
    rm -rf ${cache_root_256}/nix-static ${cache_root_256}/nix-lib ${cache_root_256}/nix-deps
    __status=$?
    exit 0
}

opt_ignore_system__218_v0() {
    >&2 echo "Ignoring system-wide Nix for testing purposes."
    __status=$?
    >&2 echo "Re-run without the --nixie-ignore-system flag to import the single-user"
    __status=$?
    >&2 echo "Nix store into the system store."
    __status=$?
    env_var_set__121_v0 "nosystem" "1"
    __status=$?
}

opt_no_precompiled__219_v0() {
    >&2 echo "Ignoring precompiled binaries for testing purposes."
    __status=$?
    >&2 echo "This implies --nixie-ignore-system."
    __status=$?
    env_var_set__121_v0 "nobins" "1"
    __status=$?
    env_var_set__121_v0 "nosystem" "1"
    __status=$?
}

notfound__220_v0() {
    local cmd_272="${1}"
    env_var_get__122_v0 "0"
    __status=$?
    local self_273="${ret_env_var_get122_v0}"
    echo_error__140_v0 "No such option: --nixie-${cmd_272}. Run '${self_273} --nixie-help' for available options." 1
}

eval_cmd__221_v0() {
    local cmd_245="${1}"
    if [ "$([ "_${cmd_245}" != "_help" ]; echo $?)" != 0 ]; then
        cmd_help__214_v0 
    elif [ "$([ "_${cmd_245}" != "_print-config" ]; echo $?)" != 0 ]; then
        cmd_print_config__215_v0 
    elif [ "$([ "_${cmd_245}" != "_extract" ]; echo $?)" != 0 ]; then
        cmd_extract__216_v0 
    elif [ "$([ "_${cmd_245}" != "_cleanup" ]; echo $?)" != 0 ]; then
        cmd_cleanup__217_v0 
    elif [ "$([ "_${cmd_245}" != "_ignore-system" ]; echo $?)" != 0 ]; then
        opt_ignore_system__218_v0 
    elif [ "$([ "_${cmd_245}" != "_no-precompiled" ]; echo $?)" != 0 ]; then
        opt_no_precompiled__219_v0 
    else
        notfound__220_v0 "${cmd_245}"
    fi
}

catch_args__222_v0() {
    local args_237=("${1}")
    eval "local args_237_deref_92=(\"\${${args_237[0]}[@]}\")"
    local local_args_238=("${args_237_deref_92[@]}")
    eval "${args_237}=()"
    for arg_239 in "${local_args_238[@]}"; do
        local cmd_240=""
        starts_with__23_v0 "${arg_239}" "--nixie-"
        local ret_starts_with23_v0__110_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__110_12}" != 0 ]; then
            local __length_35="--nixie-"
            slice__25_v0 "${arg_239}" "${#__length_35}" 0
            cmd_240="${ret_slice25_v0}"
            eval_cmd__221_v0 "${cmd_240}"
        else
            eval "${args_237}+=(\"\${arg_239}\")"
        fi
    done
}

file_download__326_v0() {
    local url_2814="${1}"
    local path_2815="${2}"
    is_command__124_v0 "curl"
    local ret_is_command124_v0__15_9="${ret_is_command124_v0}"
    is_command__124_v0 "wget"
    local ret_is_command124_v0__18_9="${ret_is_command124_v0}"
    is_command__124_v0 "aria2c"
    local ret_is_command124_v0__21_9="${ret_is_command124_v0}"
    if [ "${ret_is_command124_v0__15_9}" != 0 ]; then
        curl -L -o "${path_2815}" "${url_2814}">/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command124_v0__18_9}" != 0 ]; then
        wget "${url_2814}" -P "${path_2815}">/dev/null 2>&1
        __status=$?
    elif [ "${ret_is_command124_v0__21_9}" != 0 ]; then
        aria2c "${url_2814}" -d "${path_2815}">/dev/null 2>&1
        __status=$?
    else
        ret_file_download326_v0=''
        return 1
    fi
}

cachix_url__334_v0() {
    local derivation_2811="${1}"
    local member_2812="${2}"
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    local __SOURCE_CACHE_2813="${ret_env_var_get122_v0}"
    ret_cachix_url334_v0="https://${__SOURCE_CACHE_2813}/serve/${derivation_2811}/${member_2812}"
    return 0
}

pull_binary__336_v0() {
    local member_2805="${1}"
    local dest_2806="${2}"
    env_var_get__122_v0 "NIX_BINS_DERIVATION"
    __status=$?
    local __NIX_BINS_DERIVATION_2807="${ret_env_var_get122_v0}"
    untar__184_v0 "${member_2805}" 0
    __status=$?
    local where_2808="${ret_untar184_v0}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        local command_37
        command_37="$(mktemp -t nixie_${member_2805}_XXXXXXXX)"
        __status=$?
        local tmpf_2809="${command_37}"
        local url_2810="${__NIX_BINS_DERIVATION_2807}/${member_2805}"
        starts_with__23_v0 "${__NIX_BINS_DERIVATION_2807}" "https://"
        local ret_starts_with23_v0__91_16="${ret_starts_with23_v0}"
        if [ "$(( ! ret_starts_with23_v0__91_16 ))" != 0 ]; then
            cachix_url__334_v0 "${__NIX_BINS_DERIVATION_2807}" "${member_2805}"
            url_2810="${ret_cachix_url334_v0}"
        fi
        file_download__326_v0 "${url_2810}" "${tmpf_2809}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_binary336_v0=''
            return "${__status}"
        fi
        where_2808="${tmpf_2809}"
    fi
    mv "${where_2808}" "${dest_2806}"
    __status=$?
}

command_38="$(tput tsl)"
__status=$?
tsl_40="${command_38}"
command_39="$(tput fsl)"
__status=$?
fsl_41="${command_39}"
command_40="$(tput smcup)"
__status=$?
command_41="$(tput rmcup)"
__status=$?
env_var_get__122_v0 "TERM"
__status=$?
__TERM_44="${ret_env_var_get122_v0}"
can_set_title__353_v0() {
    local has_statusline_2832=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_44}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_42
                command_42="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_40="${command_42}"
                local command_43
                command_43="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_41="${command_43}"
            else
                has_statusline_2832=0
            fi
        else
            has_statusline_2832=0
        fi
    fi
    ret_can_set_title353_v0="${has_statusline_2832}"
    return 0
}

set_title__354_v0() {
    local title_2831="${1}"
    can_set_title__353_v0 
    local ret_can_set_title353_v0__43_8="${ret_can_set_title353_v0}"
    if [ "${ret_can_set_title353_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_40}""${title_2831}""${fsl_41}"
        __status=$?
    fi
}

command_44="$(tput tsl)"
__status=$?
tsl_45="${command_44}"
command_45="$(tput fsl)"
__status=$?
fsl_46="${command_45}"
command_46="$(tput smcup)"
__status=$?
command_47="$(tput rmcup)"
__status=$?
rmcup_48="${command_47}"
env_var_get__122_v0 "TERM"
__status=$?
__TERM_49="${ret_env_var_get122_v0}"
can_set_title__373_v0() {
    local has_statusline_2845=1
    tput hs
    __status=$?
    if [ "${__status}" != 0 ]; then
        starts_with__23_v0 "${__TERM_49}" "xterm"
        local ret_starts_with23_v0__22_12="${ret_starts_with23_v0}"
        if [ "${ret_starts_with23_v0__22_12}" != 0 ]; then
            TERM=xterm+sl tput hs
            __status=$?
            if [ "$(( __status == 0 ))" != 0 ]; then
                local command_48
                command_48="$(TERM=xterm+sl tput tsl)"
                __status=$?
                tsl_45="${command_48}"
                local command_49
                command_49="$(TERM=xterm+sl tput fsl)"
                __status=$?
                fsl_46="${command_49}"
            else
                has_statusline_2845=0
            fi
        else
            has_statusline_2845=0
        fi
    fi
    ret_can_set_title373_v0="${has_statusline_2845}"
    return 0
}

set_title__374_v0() {
    local title_2844="${1}"
    can_set_title__373_v0 
    local ret_can_set_title373_v0__43_8="${ret_can_set_title373_v0}"
    if [ "${ret_can_set_title373_v0__43_8}" != 0 ]; then
        >&2 echo "${tsl_45}""${title_2844}""${fsl_46}"
        __status=$?
    fi
}

exit_alt_buffer__376_v0() {
    >&2 echo ${rmcup_48}
    __status=$?
}

__SELF_50=""
env_var_get__122_v0 "0"
__status=$?
me_51="${ret_env_var_get122_v0}"
text_contains__17_v0 "${me_51}" "/"
ret_text_contains17_v0__15_4="${ret_text_contains17_v0}"
if [ "${ret_text_contains17_v0__15_4}" != 0 ]; then
    starts_with__23_v0 "${me_51}" "/"
    ret_starts_with23_v0__16_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__16_8}" != 0 ]; then
        __SELF_50="${me_51}"
    else
        env_var_get__122_v0 "PWD"
        __status=$?
        __PWD_52="${ret_env_var_get122_v0}"
        command_50="$(readlink ${me_51})"
        __status=$?
        if [ "${__status}" != 0 ]; then
            __SELF_50="${__PWD_52}/${me_51}"
        fi
        rl_53="${command_50}"
        starts_with__23_v0 "${rl_53}" "/"
        ret_starts_with23_v0__27_17="${ret_starts_with23_v0}"
        if [ "$([ "_${rl_53}" != "_" ]; echo $?)" != 0 ]; then
            __SELF_50="${__SELF_50}"
        elif [ "$(( ! ret_starts_with23_v0__27_17 ))" != 0 ]; then
            __SELF_50="${__PWD_52}/${rl_53}"
        else
            __SELF_50="${rl_53}"
        fi
    fi
else
    echo_error__140_v0 "This script must be run from an absolute or relative path." 1
fi
bail__381_v0() {
    local message_2842="${1}"
    local archive_2843="${2}"
    exit_alt_buffer__376_v0 
    set_title__374_v0 ""
    echo_error__140_v0 "${message_2842}" 0
    if [ "${archive_2843}" != 0 ]; then
        echo_error__140_v0 "This script can be rebuilt using the nixie tool." 0
    fi
    exit 1
    kill -ABRT $$
    __status=$?
}

get_self__382_v0() {
    ret_get_self382_v0="${__SELF_50}"
    return 0
}

dump_archive__383_v0() {
    local command_51
    command_51="$(mktemp -t nixie_XXXXXXXX.tar)"
    __status=$?
    local dest_2841="${command_51}"
    cat ${__SELF_50} | (
        read -r M
        while ! [[ "$M" =~ ^-----BEGIN\ ARCHIVE\ SECTION----- ]]
        do read -r M || return 1
        done
        gzip -d -c 2>/dev/null > ${dest_2841}
    )
    __status=$?
    if [ "${__status}" != 0 ]; then
        if [ "$(( __status != 2 ))" != 0 ]; then
            bail__381_v0 "Could not find the script's resource archive." 1
        fi
    fi
    ret_dump_archive383_v0="${dest_2841}"
    return 0
}

untar__384_v0() {
    local member_2839="${1}"
    local dump_2840="${2}"
    dump_archive__383_v0 
    local archive_2846="${ret_dump_archive383_v0}"
    local tar_cmd_2847="tar -x -f ${archive_2846} ${member_2839}"
    if [ "${dump_2840}" != 0 ]; then
        tar_cmd_2847="tar -x -O -f ${archive_2846} ${member_2839}"
    fi
    local command_52
    command_52="$(${tar_cmd_2847})"
    __status=$?
    if [ "${__status}" != 0 ]; then
        local tar_status_2848="${__status}"
        rm ${archive_2846}
        __status=$?
        ret_untar384_v0=''
        return "${tar_status_2848}"
    fi
    local tar_out_2849="${command_52}"
    rm ${archive_2846}
    __status=$?
    if [ "${dump_2840}" != 0 ]; then
        ret_untar384_v0="${tar_out_2849}"
        return 0
    else
        ret_untar384_v0="${member_2839}"
        return 0
    fi
}

get_osname__387_v0() {
    local command_53
    command_53="$(uname -s)"
    __status=$?
    ret_get_osname387_v0="${command_53}"
    return 0
}

get_cache_root__392_v0() {
    env_var_get__122_v0 "HOME"
    __status=$?
    local userhome_2825="${ret_env_var_get122_v0}"
    get_osname__387_v0 
    local osname_2826="${ret_get_osname387_v0}"
    local result_2827=""
    if [ "$([ "_${osname_2826}" != "_Darwin" ]; echo $?)" != 0 ]; then
        result_2827="${userhome_2825}/Library/Caches"
    else
        result_2827="${userhome_2825}/.cache"
    fi
    mkdir -p ${result_2827}
    __status=$?
    ret_get_cache_root392_v0="${result_2827}"
    return 0
}

get_repo_root__393_v0() {
    get_self__382_v0 
    local ret_get_self382_v0__85_24="${ret_get_self382_v0}"
    split__5_v0 "${ret_get_self382_v0__85_24}" "/"
    local self_a_2820=("${ret_split5_v0[@]}")
    array_pop__77_v0 "self_a_2820"
    __status=$?
    join__8_v0 self_a_2820[@] "/"
    local ret_join8_v0__88_26="${ret_join8_v0}"
    local self_dir_2821="/""${ret_join8_v0__88_26}"
    local command_54
    command_54="$(git -C ${self_dir_2821} rev-parse --show-toplevel)"
    __status=$?
    if [ "${__status}" != 0 ]; then
        echo_warning__139_v0 "Failed to find current Git repository, using script parent directory."
        ret_get_repo_root393_v0="${self_dir_2821}"
        return 0
    fi
    ret_get_repo_root393_v0="${command_54}"
    return 0
}

get_source_root__397_v0() {
    get_repo_root__393_v0 
    local repo_root_2822="${ret_get_repo_root393_v0}"
    ret_get_source_root397_v0="${repo_root_2822}/.nixie/sources"
    return 0
}

cachix_url__408_v0() {
    local derivation_2854="${1}"
    local member_2855="${2}"
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    local __SOURCE_CACHE_2856="${ret_env_var_get122_v0}"
    ret_cachix_url408_v0="https://${__SOURCE_CACHE_2856}/serve/${derivation_2854}/${member_2855}"
    return 0
}

pull_source_file__409_v0() {
    local member_2834="${1}"
    local dest_2835="${2}"
    env_var_get__122_v0 "SOURCE_DERIVATION"
    __status=$?
    local __SOURCE_DERIVATION_2836="${ret_env_var_get122_v0}"
    local where_2837=""
    local my_status_2838=1
    env_var_test__119_v0 "_NIXIE_TESTING_SKIP_TARBALL"
    local ret_env_var_test119_v0__37_12="${ret_env_var_test119_v0}"
    if [ "$(( ! ret_env_var_test119_v0__37_12 ))" != 0 ]; then
        untar__384_v0 "sources/${member_2834}" 0
        __status=$?
        where_2837="${ret_untar384_v0}"
        my_status_2838="${__status}"
    fi
    env_var_test__119_v0 "_NIXIE_TESTING_SOURCES_DIR"
    local ret_env_var_test119_v0__42_8="${ret_env_var_test119_v0}"
    if [ "$(( ret_env_var_test119_v0__42_8 && $(( my_status_2838 != 0 )) ))" != 0 ]; then
        env_var_get__122_v0 "_NIXIE_TESTING_SOURCES_DIR"
        __status=$?
        local srcdir_2850="${ret_env_var_get122_v0}"
        local command_55
        command_55="$(mktemp -t -d nixie_${member_2834}_XXXXXXXX)"
        __status=$?
        local tmpd_2851="${command_55}"
        file_exists__42_v0 "${srcdir_2850}/${member_2834}.tar.gz"
        local ret_file_exists42_v0__46_12="${ret_file_exists42_v0}"
        if [ "${ret_file_exists42_v0__46_12}" != 0 ]; then
            gzip -d -c ${srcdir_2850}/${member_2834}.tar.gz | tar -x -C ${tmpd_2851}
            __status=$?
            my_status_2838="${__status}"
            where_2837="${tmpd_2851}/${member_2834}"
        else
            my_status_2838=1
        fi
    fi
    if [ "$(( my_status_2838 != 0 ))" != 0 ]; then
        local command_56
        command_56="$(mktemp -t nixie_src_XXXXXXXX.tgz)"
        __status=$?
        local tmpf_2852="${command_56}"
        local command_57
        command_57="$(mktemp -t -d nixie_${member_2834}_XXXXXXXX)"
        __status=$?
        local tmpd_2853="${command_57}"
        cachix_url__408_v0 "${__SOURCE_DERIVATION_2836}" "${member_2834}.tar.gz"
        local ret_cachix_url408_v0__59_23="${ret_cachix_url408_v0}"
        file_download__326_v0 "${ret_cachix_url408_v0__59_23}" "${tmpf_2852}"
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file409_v0=''
            return "${__status}"
        fi
        gzip -d -c ${tmpf_2852} | tar -x -C ${tmpd_2853}
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_pull_source_file409_v0=''
            return "${__status}"
        fi
        rm -f ${tmpf_2852}
        __status=$?
        where_2837="${tmpd_2853}/${member_2834}"
    fi
    rm -rf ${dest_2835}
    __status=$?
    mv "${where_2837}" "${dest_2835}"
    __status=$?
}

step_current_55=1
pkg_exists__418_v0() {
    local package_2833="${1}"
    pkg-config ${package_2833}
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_pkg_exists418_v0=0
        return 0
    fi
    ret_pkg_exists418_v0=1
    return 0
}

step_title__419_v0() {
    local name_2829="${1}"
    env_var_get__122_v0 "step_total"
    __status=$?
    local step_total_2830="${ret_env_var_get122_v0}"
    clear
    __status=$?
    set_title__354_v0 "Building Nix: ${name_2829} (${step_current_55}/${step_total_2830})"
    step_current_55="$(( step_current_55 + 1 ))"
}

get_source_root__420_v0() {
    get_repo_root__393_v0 
    local repo_root_2823="${ret_get_repo_root393_v0}"
    ret_get_source_root420_v0="${repo_root_2823}/.nixie/sources"
    return 0
}

build_openssl_inner__425_v0() {
    get_dll_ext__390_v0 
    local dll_ext_508="${ret_get_dll_ext390_v0}"
    get_cache_root__392_v0 
    local cache_root_512="${ret_get_cache_root392_v0}"
    chmod +x ./config
    __status=$?
    ./config
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner425_v0=''
        return "${__status}"
    fi
    make_headers__424_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner425_v0=''
        return "${__status}"
    fi
    make libcrypto.${dll_ext_508} libcrypto.pc
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl_inner425_v0=''
        return "${__status}"
    fi
    cp ./libcrypto.* ${cache_root_512}/nix-deps/lib/
    __status=$?
    cp ./libcrypto.pc ${cache_root_512}/nix-deps/lib/pkgconfig
    __status=$?
    cp -r ./include ${cache_root_512}/nix-deps/
    __status=$?
}

build_openssl__426_v0() {
    get_source_root__420_v0 
    local source_root_2824="${ret_get_source_root420_v0}"
    get_cache_root__392_v0 
    step_title__419_v0 "libcrypto"
    pkg_exists__418_v0 "libcrypto"
    local ret_pkg_exists418_v0__56_8="${ret_pkg_exists418_v0}"
    if [ "${ret_pkg_exists418_v0__56_8}" != 0 ]; then
        ret_build_openssl426_v0=0
        return 0
    fi
    env_var_test__119_v0 "OPENSSL_LIBS"
    local ret_env_var_test119_v0__58_8="${ret_env_var_test119_v0}"
    env_var_test__119_v0 "OPENSSL_CFLAGS"
    local ret_env_var_test119_v0__58_41="${ret_env_var_test119_v0}"
    if [ "$(( ret_env_var_test119_v0__58_8 && ret_env_var_test119_v0__58_41 ))" != 0 ]; then
        ret_build_openssl426_v0=0
        return 0
    fi
    pull_source_file__409_v0 "openssl" "${source_root_2824}/openssl"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl426_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2824}/openssl && build_openssl_inner__425_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_openssl426_v0=''
        return "${__status}"
    fi
}

build_lowdown_inner__436_v0() {
    get_cache_root__392_v0 
    local cache_root_772="${ret_get_cache_root392_v0}"
    ./configure PREFIX=${cache_root_772}/nix-deps
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner436_v0=''
        return "${__status}"
    fi
    make
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner436_v0=''
        return "${__status}"
    fi
    get_osname__387_v0 
    local ret_get_osname387_v0__26_8="${ret_get_osname387_v0}"
    if [ "$([ "_${ret_get_osname387_v0__26_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        macos_build_post__435_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            ret_build_lowdown_inner436_v0=''
            return "${__status}"
        fi
    fi
    make install_shared
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown_inner436_v0=''
        return "${__status}"
    fi
}

build_lowdown__437_v0() {
    get_source_root__420_v0 
    local source_root_2866="${ret_get_source_root420_v0}"
    get_cache_root__392_v0 
    step_title__419_v0 "lowdown"
    pkg_exists__418_v0 "lowdown"
    local ret_pkg_exists418_v0__41_8="${ret_pkg_exists418_v0}"
    if [ "${ret_pkg_exists418_v0__41_8}" != 0 ]; then
        ret_build_lowdown437_v0=0
        return 0
    fi
    pull_source_file__409_v0 "lowdown" "${source_root_2866}/lowdown"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown437_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2866}/lowdown && build_lowdown_inner__436_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_lowdown437_v0=''
        return "${__status}"
    fi
}

build_nlohmann_json__446_v0() {
    get_source_root__420_v0 
    local source_root_2861="${ret_get_source_root420_v0}"
    get_cache_root__392_v0 
    local cache_root_2862="${ret_get_cache_root392_v0}"
    step_title__419_v0 "nlohmann_json"
    pkg_exists__418_v0 "nlohmann_json"
    local ret_pkg_exists418_v0__21_8="${ret_pkg_exists418_v0}"
    if [ "${ret_pkg_exists418_v0__21_8}" != 0 ]; then
        ret_build_nlohmann_json446_v0=0
        return 0
    fi
    pull_source_file__409_v0 "nlohmann_json" "${source_root_2861}/nlohmann_json"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json446_v0=''
        return "${__status}"
    fi
    local command_58
    command_58="$(grep "^version:" ${source_root_2861}/nlohmann_json/wsjcpp.yml | cut -d '"' -f 2 | cut -d 'v' -f 2)"
    __status=$?
    local version_2863="${command_58}"
    file_write__44_v0 "${cache_root_2862}/nix-deps/lib/pkgconfig/nlohmann_json.pc" "Name: nlohmann_json
Version: ${version_2863}
Description: JSON for Modern C++
Cflags: -I${source_root_2861}/nlohmann_json/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nlohmann_json446_v0=''
        return "${__status}"
    fi
}

modules_56=("predef" "chrono" "container" "context" "coroutine" "system" "thread")
find_boost_libs__455_v0() {
    local libs_2858=("${!1}")
    for lib_2859 in "${libs_2858[@]}"; do
        local libname_2860="libboost_${lib_2859}*"
        file_exists__42_v0 "/usr/lib/${libname_2860}"
        local ret_file_exists42_v0__23_20="${ret_file_exists42_v0}"
        file_exists__42_v0 "/usr/local/lib/${libname_2860}"
        local ret_file_exists42_v0__24_20="${ret_file_exists42_v0}"
        if [ "$(( ! $(( ret_file_exists42_v0__23_20 || ret_file_exists42_v0__24_20 )) ))" != 0 ]; then
            ret_find_boost_libs455_v0=0
            return 0
        fi
        dir_exists__41_v0 "/usr/include/boost/${lib_2859}"
        local ret_dir_exists41_v0__26_20="${ret_dir_exists41_v0}"
        dir_exists__41_v0 "/usr/local/include/boost/${lib_2859}"
        local ret_dir_exists41_v0__27_20="${ret_dir_exists41_v0}"
        if [ "$(( ! $(( ret_dir_exists41_v0__26_20 || ret_dir_exists41_v0__27_20 )) ))" != 0 ]; then
            ret_find_boost_libs455_v0=0
            return 0
        fi
    done
    ret_find_boost_libs455_v0=1
    return 0
}

build_boost_inner__456_v0() {
    local args_601=("variant=release" "link=static" "--stagedir=.")
    for mod_602 in "${modules_56[@]}"; do
        args_601+=("--with-${mod_602}")
    done
    ./bootstrap.sh
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner456_v0=''
        return "${__status}"
    fi
    ./b2 "${args_601[@]}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost_inner456_v0=''
        return "${__status}"
    fi
}

build_boost__457_v0() {
    get_source_root__420_v0 
    local source_root_2857="${ret_get_source_root420_v0}"
    step_title__419_v0 "boost"
    local array_62=("atomic")
    local array_add_63=("${array_62[@]}" "${modules_56[@]}")
    find_boost_libs__455_v0 array_add_63[@]
    local ret_find_boost_libs455_v0__56_8="${ret_find_boost_libs455_v0}"
    if [ "${ret_find_boost_libs455_v0__56_8}" != 0 ]; then
        ret_build_boost457_v0=0
        return 0
    fi
    pull_source_file__409_v0 "boost" "${source_root_2857}/boost"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost457_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2857}/boost && build_boost_inner__456_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_boost457_v0=''
        return "${__status}"
    fi
    env_var_set__121_v0 "BOOST_ROOT" "${source_root_2857}/boost"
    __status=$?
    export BOOST_ROOT
    __status=$?
}

build_autoconf_dep__465_v0() {
    local lib_name_2868="${1}"
    local inc_prefix_2869="${2}"
    get_source_root__420_v0 
    local source_root_2870="${ret_get_source_root420_v0}"
    get_cache_root__392_v0 
    local cache_root_2871="${ret_get_cache_root392_v0}"
    local my_source_2872="${source_root_2870}/${lib_name_2868}"
    step_title__419_v0 "${lib_name_2868}"
    pkg_exists__418_v0 "${lib_name_2868}"
    local ret_pkg_exists418_v0__26_8="${ret_pkg_exists418_v0}"
    if [ "${ret_pkg_exists418_v0__26_8}" != 0 ]; then
        ret_build_autoconf_dep465_v0=''
        return 0
    fi
    pull_source_file__409_v0 "${lib_name_2868}" "${my_source_2872}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep465_v0=''
        return "${__status}"
    fi
    ( unset C_INCLUDE_PATH CPLUS_INCLUDE_PATH     && cd ${my_source_2872}     && ./configure --prefix=${cache_root_2871}/nix-deps     && make && make install )
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_autoconf_dep465_v0=''
        return "${__status}"
    fi
}

build_nix_inner__475_v0() {
    get_source_root__420_v0 
    local source_root_1071="${ret_get_source_root420_v0}"
    local venv_1072="${source_root_1071}/nix/venv"
    mkdir build && cd build
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner475_v0=''
        return "${__status}"
    fi
    ${venv_1072}/bin/meson setup -Dlibstore:seccomp-sandboxing=disabled                             -Dlibcmd:readline-flavor=editline                             -Dlibexpr:gc=disabled                             -Dlibutil:cpuid=disabled                             -Ddoc-gen=false                             -Dunit-tests=false                             -Dbindings=false                             ..
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner475_v0=''
        return "${__status}"
    fi
    ${venv_1072}/bin/ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix_inner475_v0=''
        return "${__status}"
    fi
}

build_nix__476_v0() {
    get_source_root__420_v0 
    local source_root_2873="${ret_get_source_root420_v0}"
    get_cache_root__392_v0 
    local cache_root_2874="${ret_get_cache_root392_v0}"
    local venv_2875="${source_root_2873}/nix/venv"
    step_title__419_v0 "nix"
    pull_source_file__409_v0 "nix" "${source_root_2873}/nix"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix476_v0=''
        return "${__status}"
    fi
    python3 -m venv --system-site-packages "${venv_2875}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix476_v0=''
        return "${__status}"
    fi
    export LIBRARY_PATH=${cache_root_2874}/nix-deps/lib:$LIBRARY_PATH
    __status=$?
    export PKG_CONFIG_PATH=${cache_root_2874}/nix-deps/lib/pkgconfig:${cache_root_2874}/nix-deps/share/pkgconfig:$PKG_CONFIG_PATH
    __status=$?
    ${venv_2875}/bin/pip install meson ninja
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix476_v0=''
        return "${__status}"
    fi
    (cd ${source_root_2873}/nix && build_nix_inner__475_v0)
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_build_nix476_v0=''
        return "${__status}"
    fi
    mv "${source_root_2873}/nix/src/nix/nix" "${cache_root_2874}/nix-static"
    __status=$?
}

darwin_export_sdk__478_v0() {
    local command_64
    command_64="$(xcrun --show-sdk-path)"
    __status=$?
    local sdk_path_2817="${command_64}"
    dir_exists__41_v0 "${sdk_path_2817}"
    local ret_dir_exists41_v0__30_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__30_12 ))" != 0 ]; then
        bail__181_v0 "The macOS SDK from Xcode or CommandLineTools is required to build Nix." 0
    fi
    local sdk_libs_2818="${sdk_path_2817}/usr/lib"
    local sdk_cflags_2819="-I${sdk_path_2817}/usr/include"
    env_var_set__121_v0 "LIBCURL_LIBS" "${sdk_libs_2818}"
    __status=$?
    env_var_set__121_v0 "LIBCURL_CFLAGS" "${sdk_cflags_2819}"
    __status=$?
    env_var_set__121_v0 "LIBARCHIVE_LIBS" "${sdk_libs_2818}"
    __status=$?
    env_var_set__121_v0 "LIBARCHIVE_CFLAGS" "${sdk_cflags_2819}"
    __status=$?
    env_var_set__121_v0 "OPENSSL_LIBS" "${sdk_libs_2818}"
    __status=$?
    env_var_set__121_v0 "OPENSSL_CFLAGS" "${sdk_cflags_2819}"
    __status=$?
    export LIBCURL_LIBS LIBCURL_CFLAGS                   LIBARCHIVE_LIBS LIBARCHIVE_CFLAGS                   OPENSSL_LIBS OPENSSL_CFLAGS
    __status=$?
}

try_build_nix__479_v0() {
    get_cache_root__200_v0 
    local cache_root_2816="${ret_get_cache_root200_v0}"
    local array_65=("cc" "c++" "pkg-config" "make" "flex" "bison" "perl")
    check_deps__185_v0 array_65[@]
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "Missing required dependencies to build from source." 0
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__60_8="${ret_get_osname195_v0}"
    if [ "$([ "_${ret_get_osname195_v0__60_8}" != "_Darwin" ]; echo $?)" != 0 ]; then
        darwin_export_sdk__478_v0 
    fi
    env_var_set__121_v0 "step_total" "9"
    __status=$?
    get_source_root__397_v0 
    local ret_get_source_root397_v0__65_22="${ret_get_source_root397_v0}"
    dir_create__47_v0 "${ret_get_source_root397_v0__65_22}"
    __status=$?
    dir_create__47_v0 "${cache_root_2816}/nix-deps/lib/pkgconfig"
    __status=$?
    build_openssl__426_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_boost__457_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_nlohmann_json__446_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_lowdown__437_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__465_v0 "libbrotlicommon" "c/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__465_v0 "libsodium" "src/libsodium/include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__465_v0 "libeditline" "include"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_autoconf_dep__465_v0 "libarchive" "libarchive"
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
    build_nix__476_v0 
    __status=$?
    if [ "${__status}" != 0 ]; then
        ret_try_build_nix479_v0=''
        return "${__status}"
    fi
}

is_nix_installed__481_v0() {
    env_var_test__119_v0 "nosystem"
    local ret_env_var_test119_v0__24_8="${ret_env_var_test119_v0}"
    if [ "${ret_env_var_test119_v0__24_8}" != 0 ]; then
        ret_is_nix_installed481_v0=0
        return 0
    fi
    dir_exists__41_v0 "/nix/store"
    local ret_dir_exists41_v0__29_8="${ret_dir_exists41_v0}"
    if [ "${ret_dir_exists41_v0__29_8}" != 0 ]; then
        ret_is_nix_installed481_v0=1
        return 0
    fi
    ret_is_nix_installed481_v0=0
    return 0
}

get_nix__482_v0() {
    get_cache_root__200_v0 
    local cache_root_2794="${ret_get_cache_root200_v0}"
    get_osname__195_v0 
    local osname_2795="${ret_get_osname195_v0}"
    get_system__197_v0 
    local system_2799="${ret_get_system197_v0}"
    local nix_path_2800="${cache_root_2794}/nix-static"
    local fakedir_path_2801="${cache_root_2794}/nix-deps/lib/libfakedir.dylib"
    local cache_id_2802="${cache_root_2794}/nix-static.id"
    env_var_get__122_v0 "NIX_BINS_DERIVATION"
    __status=$?
    local bins_drv_2803="${ret_env_var_get122_v0}"
    local cached_2804=0
    file_exists__42_v0 "${cache_id_2802}"
    local ret_file_exists42_v0__53_8="${ret_file_exists42_v0}"
    if [ "${ret_file_exists42_v0__53_8}" != 0 ]; then
        local command_66
        command_66="$(cat ${cache_id_2802})"
        __status=$?
        cached_2804="$([ "_${command_66}" != "_${bins_drv_2803}" ]; echo $?)"
    fi
    enter_alt_buffer__175_v0 
    set_title__174_v0 "Building Nix..."
    trap "teardown__177_v0; exit 1" SIGKILL SIGTERM SIGINT SIGABRT
    __status=$?
    if [ "$([ "_${osname_2795}" != "_Darwin" ]; echo $?)" != 0 ]; then
        file_exists__42_v0 "${fakedir_path_2801}"
        local ret_file_exists42_v0__64_30="${ret_file_exists42_v0}"
        if [ "$(( $(( ! cached_2804 )) || $(( ! ret_file_exists42_v0__64_30 )) ))" != 0 ]; then
            dir_create__47_v0 "${cache_root_2794}/nix-deps/lib"
            __status=$?
            pull_binary__336_v0 "libfakedir.dylib" "${fakedir_path_2801}"
            __status=$?
            if [ "${__status}" != 0 ]; then
                teardown__177_v0 1
                ret_get_nix482_v0=''
                return 1
            fi
        fi
    fi
    file_exists__42_v0 "${nix_path_2800}"
    local ret_file_exists42_v0__74_19="${ret_file_exists42_v0}"
    if [ "$(( cached_2804 && ret_file_exists42_v0__74_19 ))" != 0 ]; then
        teardown__177_v0 0
        ret_get_nix482_v0=0
        return 0
    fi
    env_var_test__119_v0 "nobins"
    local ret_env_var_test119_v0__79_8="${ret_env_var_test119_v0}"
    if [ "${ret_env_var_test119_v0__79_8}" != 0 ]; then
        try_build_nix__479_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__177_v0 1
            ret_get_nix482_v0=''
            return 1
        fi
    fi
    pull_binary__336_v0 "nix.${system_2799}" "${nix_path_2800}"
    __status=$?
    if [ "${__status}" != 0 ]; then
        try_build_nix__479_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            teardown__177_v0 1
            ret_get_nix482_v0=''
            return 1
        fi
    fi
    chmod +x ${nix_path_2800}
    __status=$?
    echo ${bins_drv_2803} > ${cache_id_2802}
    __status=$?
    teardown__177_v0 0
    ret_get_nix482_v0=0
    return 0
}

migrate_nix_store__483_v0() {
    get_nix_root__199_v0 
    local ret_get_nix_root199_v0__109_36="${ret_get_nix_root199_v0}"
    local command_67
    command_67="$(readlink -f ${ret_get_nix_root199_v0__109_36})"
    __status=$?
    nix_root_2793="${command_67}"
    if [ "$(( __status != 0 ))" != 0 ]; then
        get_nix_root__199_v0 
        nix_root_2793="${ret_get_nix_root199_v0}"
    fi
    dir_exists__41_v0 "${nix_root_2793}/nix/store"
    local ret_dir_exists41_v0__114_12="${ret_dir_exists41_v0}"
    if [ "$(( ! ret_dir_exists41_v0__114_12 ))" != 0 ]; then
        ret_migrate_nix_store483_v0=0
        return 0
    fi
    >&2 echo "Migrating Nix store to system-wide install..."
    __status=$?
    nix --extra-experimental-features nix-command copy --from ${nix_root_2793} --all --no-check-sigs
    __status=$?
    if [ "$(( __status == 0 ))" != 0 ]; then
        chmod -R +wx ${nix_root_2793} && rm -rf ${nix_root_2793}
        __status=$?
    fi
}

unpack_channels__484_v0() {
    get_repo_root__201_v0 
    local repo_root_2785="${ret_get_repo_root201_v0}"
    get_self__182_v0 
    local ret_get_self182_v0__130_52="${ret_get_self182_v0}"
    exists_newer__180_v0 "${repo_root_2785}/.nixie/channels" "${ret_get_self182_v0__130_52}"
    local ret_exists_newer180_v0__130_8="${ret_exists_newer180_v0}"
    if [ "${ret_exists_newer180_v0__130_8}" != 0 ]; then
        env_var_get__122_v0 "NIX_PATH"
        __status=$?
        local __NIX_PATH_2792="${ret_env_var_get122_v0}"
        env_var_set__121_v0 "NIX_PATH" "${repo_root_2785}/.nixie/channels:${__NIX_PATH_2792}"
        __status=$?
        export NIX_PATH
        __status=$?
        ret_unpack_channels484_v0=0
        return 0
    fi
    echo "Unpacking Nix channels, hang tight..."
    dir_create__47_v0 "${repo_root_2785}/.nixie"
    __status=$?
    untar__184_v0 "-C ${repo_root_2785}/.nixie channels" 0
    __status=$?
    if [ "${__status}" != 0 ]; then
        mkdir ${repo_root_2785}/.nixie/channels
        __status=$?
    fi
}

populate_extras__485_v0() {
    local args_2775=()
    env_var_get__122_v0 "EXTRA_FEATURES"
    __status=$?
    local __EXTRA_FEATURES_2776="${ret_env_var_get122_v0}"
    env_var_get__122_v0 "EXTRA_SUBSTITUTERS"
    __status=$?
    local __EXTRA_SUBSTITUTERS_2777="${ret_env_var_get122_v0}"
    env_var_get__122_v0 "EXTRA_TRUSTED_PUBLIC_KEYS"
    __status=$?
    local __EXTRA_TRUSTED_PUBLIC_KEYS_2778="${ret_env_var_get122_v0}"
    get_nix_root__199_v0 
    local nix_root_2779="${ret_get_nix_root199_v0}"
    if [ "$([ "_${__EXTRA_FEATURES_2776}" == "_" ]; echo $?)" != 0 ]; then
        args_2775+=("--extra-experimental-features" "${__EXTRA_FEATURES_2776}")
    fi
    if [ "$([ "_${__EXTRA_SUBSTITUTERS_2777}" == "_" ]; echo $?)" != 0 ]; then
        args_2775+=("--extra-substituters" "${__EXTRA_SUBSTITUTERS_2777}")
    fi
    if [ "$([ "_${__EXTRA_TRUSTED_PUBLIC_KEYS_2778}" == "_" ]; echo $?)" != 0 ]; then
        args_2775+=("--extra-trusted-public-keys" "${__EXTRA_TRUSTED_PUBLIC_KEYS_2778}")
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__166_8="${ret_get_osname195_v0}"
    is_nix_installed__481_v0 
    local ret_is_nix_installed481_v0__166_41="${ret_is_nix_installed481_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__166_8}" == "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed481_v0__166_41 )) ))" != 0 ]; then
        local command_73
        command_73="$(readlink -f ${nix_root_2779})"
        __status=$?
        args_2775+=("--store" "${command_73}")
    fi
    ret_populate_extras485_v0=("${args_2775[@]}")
    return 0
}

launch_darwin_workaround__486_v0() {
    local name_2890="${1}"
    local nix_path_2891="${2}"
    local args_2892=("${!3}")
    get_cache_root__200_v0 
    local cache_root_2893="${ret_get_cache_root200_v0}"
    get_nix_root__199_v0 
    local nix_root_2894="${ret_get_nix_root199_v0}"
    local fakedir_path_2895="${cache_root_2893}/nix-deps/lib/libfakedir.dylib"
    env_var_set__121_v0 "FAKEDIR_PATTERN" "/nix"
    __status=$?
    env_var_set__121_v0 "FAKEDIR_TARGET" "${nix_root_2894}/nix"
    __status=$?
    export FAKEDIR_PATTERN FAKEDIR_TARGET
    __status=$?
    _NIX_TEST_NO_SANDBOX=1             DYLD_INSERT_LIBRARIES="${fakedir_path_2895}"             DYLD_LIBRARY_PATH="${cache_root_2893}/nix-deps/lib"                 exec -a ${name_2890} "${nix_path_2891}" "${args_2892[@]}"
    __status=$?
}

launch_shell_command__487_v0() {
    local nix_path_2896="${1}"
    local cmd_2897="${2}"
    local extras_2898=("${!3}")
    local args_2899=("${!4}")
    get_repo_root__201_v0 
    local repo_root_2900="${ret_get_repo_root201_v0}"
    env_var_get__122_v0 "PWD"
    __status=$?
    local pwd_2901="${ret_env_var_get122_v0}"
    local name_2902="nix-shell"
    local shell_cmd_2903=("${repo_root_2900}/shell.nix" "--command" "${cmd_2897} ${args_2899[@]}")
    file_exists__42_v0 "${pwd_2901}/flake.nix"
    local ret_file_exists42_v0__215_8="${ret_file_exists42_v0}"
    if [ "${ret_file_exists42_v0__215_8}" != 0 ]; then
        name_2902="nix"
        local array_75=("develop" "${pwd_2901}" "-c" "${cmd_2897}")
        shell_cmd_2903=("${array_75[@]}" "${args_2899[@]}")
    else
        file_exists__42_v0 "${repo_root_2900}/flake.nix"
        local ret_file_exists42_v0__218_16="${ret_file_exists42_v0}"
        if [ "${ret_file_exists42_v0__218_16}" != 0 ]; then
            name_2902="nix"
            local array_77=("develop" "${repo_root_2900}" "-c" "${cmd_2897}")
            shell_cmd_2903=("${array_77[@]}" "${args_2899[@]}")
        else
            file_exists__42_v0 "${pwd_2901}/shell.nix"
            local ret_file_exists42_v0__221_16="${ret_file_exists42_v0}"
            if [ "${ret_file_exists42_v0__221_16}" != 0 ]; then
                shell_cmd_2903=("${pwd_2901}/shell.nix" "--command" "${cmd_2897} ${args_2899[@]}")
            fi
        fi
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__225_8="${ret_get_osname195_v0}"
    is_nix_installed__481_v0 
    local ret_is_nix_installed481_v0__225_41="${ret_is_nix_installed481_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__225_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed481_v0__225_41 )) ))" != 0 ]; then
        local array_add_80=("${extras_2898[@]}" "${shell_cmd_2903[@]}")
        launch_darwin_workaround__486_v0 "${name_2902}" "${nix_path_2896}" array_add_80[@]
    else
        exec -a ${name_2902} ${nix_path_2896} "${extras_2898[@]}" "${shell_cmd_2903[@]}"
        __status=$?
    fi
}

launch_nix_shebang__488_v0() {
    local nix_path_2879="${1}"
    local file_2880="${2}"
    local extras_2881=("${!3}")
    local args_2882=("${!4}")
    local shebang_2883=""
    i_2885=0;
    while IFS= read -r line_2884 || [ -n "$line_2884" ]; do
        if [ "$(( i_2885 == 1 ))" != 0 ]; then
            shebang_2883="${line_2884}"
            break
        fi
        (( i_2885++ )) || true
    done <"${file_2880}"
    starts_with__23_v0 "${shebang_2883}" "#"'!'""
    local ret_starts_with23_v0__252_12="${ret_starts_with23_v0}"
    if [ "$(( ! ret_starts_with23_v0__252_12 ))" != 0 ]; then
        ret_launch_nix_shebang488_v0=''
        return 0
    fi
    slice__25_v0 "${shebang_2883}" 2 0
    local ret_slice25_v0__254_27="${ret_slice25_v0}"
    split__5_v0 "${ret_slice25_v0__254_27}" " "
    local bang_args_2886=("${ret_split5_v0[@]}")
    array_shift__78_v0 "bang_args_2886"
    __status=$?
    local name_2887="${ret_array_shift78_v0}"
    i_2889=0;
    for arg_2888 in "${bang_args_2886[@]}"; do
        if [ "$([ "_${arg_2888}" != "_-i" ]; echo $?)" != 0 ]; then
            bang_args_2886["${i_2889}"]="--command"
            bang_args_2886["$(( i_2889 + 1 ))"]="${bang_args_2886[$(( i_2889 + 1 ))]} ${file_2880} ${args_2882[@]}"
            break
        fi
        (( i_2889++ )) || true
    done
    get_osname__195_v0 
    local ret_get_osname195_v0__266_8="${ret_get_osname195_v0}"
    is_nix_installed__481_v0 
    local ret_is_nix_installed481_v0__266_41="${ret_is_nix_installed481_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__266_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed481_v0__266_41 )) ))" != 0 ]; then
        local array_add_81=("${extras_2881[@]}" "${bang_args_2886[@]}")
        launch_darwin_workaround__486_v0 "${name_2887}" "${nix_path_2879}" array_add_81[@]
    else
        exec -a ${name_2887} ${nix_path_2879} "${extras_2881[@]}" "${bang_args_2886[@]}"
        __status=$?
    fi
}

launch_nix__489_v0() {
    local self_2770="${1}"
    local args_2771=("${!2}")
    get_cache_root__200_v0 
    local cache_root_2772="${ret_get_cache_root200_v0}"
    get_nix_root__199_v0 
    local nix_path_2774="${cache_root_2772}/nix-static"
    populate_extras__485_v0 
    local extras_2781=("${ret_populate_extras485_v0[@]}")
    split__5_v0 "${self_2770}" "/"
    local ret_split5_v0__283_33=("${ret_split5_v0[@]}")
    array_last__74_v0 ret_split5_v0__283_33[@]
    __status=$?
    local name_2784="${ret_array_last74_v0}"
    starts_with__23_v0 "${name_2784}" "nix-"
    local ret_starts_with23_v0__285_8="${ret_starts_with23_v0}"
    if [ "${ret_starts_with23_v0__285_8}" != 0 ]; then
        unpack_channels__484_v0 
    fi
    is_nix_installed__481_v0 
    local ret_is_nix_installed481_v0__288_8="${ret_is_nix_installed481_v0}"
    if [ "${ret_is_nix_installed481_v0__288_8}" != 0 ]; then
        migrate_nix_store__483_v0 
        nix_path_2774="nix"
    else
        get_nix__482_v0 
        __status=$?
        if [ "${__status}" != 0 ]; then
            bail__181_v0 "Failed to obtain Nix. Check your internet connection." 0
        fi
    fi
    export NIX_SSL_CERT_FILE
    __status=$?
    file_exists__42_v0 "${args_2771[0]}"
    local ret_file_exists42_v0__299_8="${ret_file_exists42_v0}"
    ends_with__24_v0 "${args_2771[0]}" ".nix"
    local ret_ends_with24_v0__299_37="${ret_ends_with24_v0}"
    if [ "$(( ret_file_exists42_v0__299_8 && $(( ! ret_ends_with24_v0__299_37 )) ))" != 0 ]; then
        local args_shebang_2878=("${args_2771[@]}")
        array_shift__78_v0 "args_shebang_2878"
        __status=$?
        launch_nix_shebang__488_v0 "${nix_path_2774}" "${args_2771[0]}" extras_2781[@] args_shebang_2878[@]
    fi
    starts_with__23_v0 "${name_2784}" "nix"
    local ret_starts_with23_v0__305_12="${ret_starts_with23_v0}"
    if [ "$(( ! ret_starts_with23_v0__305_12 ))" != 0 ]; then
        launch_shell_command__487_v0 "${nix_path_2774}" "${name_2784}" extras_2781[@] args_2771[@]
    fi
    get_osname__195_v0 
    local ret_get_osname195_v0__309_8="${ret_get_osname195_v0}"
    is_nix_installed__481_v0 
    local ret_is_nix_installed481_v0__309_41="${ret_is_nix_installed481_v0}"
    if [ "$(( $([ "_${ret_get_osname195_v0__309_8}" != "_Darwin" ]; echo $?) && $(( ! ret_is_nix_installed481_v0__309_41 )) ))" != 0 ]; then
        local array_add_82=("${extras_2781[@]}" "${args_2771[@]}")
        launch_darwin_workaround__486_v0 "${name_2784}" "${nix_path_2774}" array_add_82[@]
    else
        exec -a ${name_2784} ${nix_path_2774} "${extras_2781[@]}" "${args_2771[@]}"
        __status=$?
    fi
}

array_84=("tar" "gzip" "uname")
check_deps__185_v0 array_84[@]
__status=$?
if [ "${__status}" != 0 ]; then
    exit 1
fi
load_features__491_v0() {
    untar__184_v0 "features" 1
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "The resource archive is missing or malformed." 1
    fi
    local envfile_123="${ret_untar184_v0}"
    eval ${envfile_123}
    __status=$?
    if [ "${__status}" != 0 ]; then
        bail__181_v0 "The environment file in the resource archive is malformed." 1
    fi
    env_var_get__122_v0 "SOURCE_CACHE"
    __status=$?
    env_var_get__122_v0 "SOURCE_DERIVATION"
    __status=$?
    env_var_get__122_v0 "NIX_BINS_DERIVATION"
    __status=$?
    env_var_get__122_v0 "EXTRA_FEATURES"
    __status=$?
    env_var_get__122_v0 "EXTRA_SUBSTITUTERS"
    __status=$?
    env_var_get__122_v0 "EXTRA_TRUSTED_PUBLIC_KEYS"
    __status=$?
    env_var_get__122_v0 "NIXIE_VERSION"
    __status=$?
}

declare -r cmdl_68=("$0" "$@")
args_7=("${cmdl_68[@]}")
load_features__491_v0 
catch_args__222_v0 "args_7"
array_shift__78_v0 "args_7"
__status=$?
self_280="${ret_array_shift78_v0}"
file_exists__42_v0 "/etc/pki/tls/certs/ca-bundle.crt"
ret_file_exists42_v0__68_5="${ret_file_exists42_v0}"
get_osname__195_v0 
ret_get_osname195_v0__70_5="${ret_get_osname195_v0}"
if [ "${ret_file_exists42_v0__68_5}" != 0 ]; then
    env_var_set__121_v0 "NIX_SSL_CERT_FILE" "/etc/pki/tls/certs/ca-bundle.crt"
    __status=$?
elif [ "$([ "_${ret_get_osname195_v0__70_5}" != "_Darwin" ]; echo $?)" != 0 ]; then
    env_var_set__121_v0 "NIX_SSL_CERT_FILE" "/etc/ssl/cert.pem"
    __status=$?
fi
launch_nix__489_v0 "${self_280}" args_7[@]
exit 0
cat <<DONOTPARSE

-----BEGIN ARCHIVE SECTION-----[?1049h
ãrû†jˇ ÌœMoÇ@`Œ˛
√ùOøjà€î¥±cOd≈∂U0,T⁄__‘höﬁ€˙>óŸÃŒÓÃ$úUu…•ÚÉÃ÷∞ﬂ?≈÷˜hˆG√Î˘ú¨Å“5ï_PÀäïmKÂ"+Í;—qhËì`¢Ê¢—‚b∑c˘¶õlŸ+ójÁ\Ñ”Äz4§ƒoÎ.YÍá%≥hN=7z œßÀ‡)Ù]πé{OŒüJ∂◊cg¢—ã2ΩñÃàÔ-Í=Õ'À>ﬁ≠^nΩ¨Eûå“,ŸoÏ$µ‰[*7„qgÓ≠¢©7æ>R≥™⁄À[√(ŸAOEï’ÎZÚ2.ÚäÁïﬁÓb–¢ÒB‰‹h‹HDcÏX\H≠,äjÀ•‘é⁄zo`¥ùY)∏4.›Vè}=-€≈èm”ÍfOcVG                 ¯3ü∂∞¥» (  [?1049l [2K[37;2m# (tarball data)[0m